-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS 3dmanager; USE 3dmanager;

-- CREATE TABLES
CREATE TABLE `3DMANAGER_C_ROLES` (
  `3DMANAGER_C_ROLES_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_C_ROLES_NAME` varchar(30) NOT NULL,
  PRIMARY KEY (`3DMANAGER_C_ROLES_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_C_STATE_FILAMENT` (
  `3DMANAGER_C_STATE_FILAMENT_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_C_STATE_FILAMENT_NAME` varchar(50) NOT NULL,
  PRIMARY KEY (`3DMANAGER_C_STATE_FILAMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_C_STATE_PRINT` (
  `3DMANAGER_C_STATE_PRINT_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_C_STATE_PRINT_NAME` varchar(50) NOT NULL,
  PRIMARY KEY (`3DMANAGER_C_STATE_PRINT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_C_STATE_PRINTER` (
  `3DMANAGER_C_STATE_PRINTER_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_C_STATE_PRINTER_NAME` varchar(50) NOT NULL,
  PRIMARY KEY (`3DMANAGER_C_STATE_PRINTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_C_TYPE_FILAMENT` (
  `3DMANAGER_C_TYPE_FILAMENT_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_C_TYPE_FILAMENT_NAME` varchar(30) NOT NULL,
  PRIMARY KEY (`3DMANAGER_C_TYPE_FILAMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_C_TYPE_NOTIFICATION` (
  `3DMANAGER_C_TYPE_NOTIFICATION_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_C_TYPE_NOTIFICATION_NAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`3DMANAGER_C_TYPE_NOTIFICATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `3DMANAGER_GROUP` (
  `3DMANAGER_GROUP_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_GROUP_NAME` varchar(100) NOT NULL,
  `3DMANAGER_GROUP_DESCRIPTION` varchar(500) DEFAULT NULL,
  `3DMANAGER_PRINTER_REGISTER_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `3DMANAGER_USER_OWNER` int NOT NULL,
  PRIMARY KEY (`3DMANAGER_GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_USER` (
  `USER_ID` int NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(100) NOT NULL,
  `USER_PASSWORD` varchar(255) NOT NULL,
  `USER_EMAIL` varchar(100) NOT NULL,
  `USER_ROLE` int DEFAULT NULL,
  `USER_GROUP_ID` int DEFAULT NULL,
  `USER_PHOTO_URL` varchar(255) DEFAULT NULL,
  `USER_REGISTER_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`),
  KEY `FK_USER_GROUP_idx` (`USER_GROUP_ID`),
  KEY `FK_USER_ROLE_idx` (`USER_ROLE`),
  CONSTRAINT `FK_USER_GROUP` FOREIGN KEY (`USER_GROUP_ID`) REFERENCES `3DMANAGER_GROUP` (`3DMANAGER_GROUP_ID`),
  CONSTRAINT `FK_USER_ROLE` FOREIGN KEY (`USER_ROLE`) REFERENCES `3DMANAGER_C_ROLES` (`3DMANAGER_C_ROLES_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_FILAMENT` (
  `3DMANAGER_FILAMENT_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_FILAMENT_NAME` varchar(100) NOT NULL,
  `3DMANAGER_FILAMENT_DESCRIPTION` varchar(500) DEFAULT NULL,
  `3DMANAGER_FILAMENT_STATE` int NOT NULL,
  `3DMANAGER_FILAMENT_MATERIAL_LENGTH` decimal(10,4) NOT NULL,
  `3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH` decimal(10,4) NOT NULL,
  `3DMANAGER_FILAMENT_MATERIAL_THICKNESS` float DEFAULT NULL,
  `3DMANAGER_FILAMENT_TEMPERATURE` int DEFAULT NULL,
  `3DMANAGER_FILAMENT_COLOR` varchar(10) DEFAULT NULL,
  `3DMANAGER_FILAMENT_GROUP_ID` int NOT NULL,
  `3DMANAGER_FILAMENT_MATERIAL_TYPE` int NOT NULL,
  `3DMANAGER_FILAMENT_REGISTER_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `3DMANAGER_FILAMENT_WEIGHT` int DEFAULT NULL,
  `3DMANAGER_FILAMENT_COST` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`3DMANAGER_FILAMENT_ID`),
  KEY `FK_FILAMENT_STATE_idx` (`3DMANAGER_FILAMENT_STATE`),
  KEY `FK_FILAMENT_MATERIAL_idx` (`3DMANAGER_FILAMENT_MATERIAL_TYPE`),
  KEY `FK_FILAMENT_GROUP_idx` (`3DMANAGER_FILAMENT_GROUP_ID`),
  CONSTRAINT `FK_FILAMENT_GROUP` FOREIGN KEY (`3DMANAGER_FILAMENT_GROUP_ID`) REFERENCES `3DMANAGER_GROUP` (`3DMANAGER_GROUP_ID`),
  CONSTRAINT `FK_FILAMENT_MATERIAL` FOREIGN KEY (`3DMANAGER_FILAMENT_MATERIAL_TYPE`) REFERENCES `3DMANAGER_C_TYPE_FILAMENT` (`3DMANAGER_C_TYPE_FILAMENT_ID`),
  CONSTRAINT `FK_FILAMENT_STATE` FOREIGN KEY (`3DMANAGER_FILAMENT_STATE`) REFERENCES `3DMANAGER_C_STATE_FILAMENT` (`3DMANAGER_C_STATE_FILAMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_PRINTER` (
  `3DMANAGER_PRINTER_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_PRINTER_NAME` varchar(100) NOT NULL,
  `3DMANAGER_PRINTER_MODEL` varchar(100) DEFAULT NULL,
  `3DMANAGER_PRINTER_TIME_VARIATION` float DEFAULT NULL,
  `3DMANAGER_PRINTER_STATE` int DEFAULT NULL,
  `3DMANAGER_PRINTER_GROUP_ID` int DEFAULT NULL,
  `3DMANAGER_PRINTER_REGISTER_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `3DMANAGER_PRINTER_DESCRIPTION` varchar(100) DEFAULT NULL,
  `3DMANAGER_PRINTER_IMAGE_URL` varchar(255) DEFAULT NULL,
  `3DMANAGER_PRINTER_IMAGE_KEY` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`3DMANAGER_PRINTER_ID`),
  KEY `FK_PRINTER_GROUP_idx` (`3DMANAGER_PRINTER_GROUP_ID`),
  KEY `FK_PRINTER_STATE_idx` (`3DMANAGER_PRINTER_STATE`),
  CONSTRAINT `FK_PRINTER_GROUP` FOREIGN KEY (`3DMANAGER_PRINTER_GROUP_ID`) REFERENCES `3DMANAGER_GROUP` (`3DMANAGER_GROUP_ID`),
  CONSTRAINT `FK_PRINTER_STATE` FOREIGN KEY (`3DMANAGER_PRINTER_STATE`) REFERENCES `3DMANAGER_C_STATE_PRINTER` (`3DMANAGER_C_STATE_PRINTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `3DMANAGER_INVITATIONS` (
  `3DMANAGER_INVITATIONS_USER_ID` int NOT NULL,
  `3DMANAGER_INVITATIONS_GROUP_ID` int NOT NULL,
  PRIMARY KEY (`3DMANAGER_INVITATIONS_GROUP_ID`,`3DMANAGER_INVITATIONS_USER_ID`),
  KEY `FK_INVITATION_USER` (`3DMANAGER_INVITATIONS_USER_ID`),
  CONSTRAINT `FK_INVITATION_GROUP` FOREIGN KEY (`3DMANAGER_INVITATIONS_GROUP_ID`) REFERENCES `3DMANAGER_GROUP` (`3DMANAGER_GROUP_ID`),
  CONSTRAINT `FK_INVITATION_USER` FOREIGN KEY (`3DMANAGER_INVITATIONS_USER_ID`) REFERENCES `3DMANAGER_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_NOTIFICATION` (
  `3DMANAGER_NOTIFICATION_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_NOTIFICATION_IT_READ` bit(1) NOT NULL,
  `3DMANAGER_NOTIFICATION_MESSAGE` varchar(500) NOT NULL,
  `3DMANAGER_NOTIFICATION_REGISTER_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `3DMANAGER_NOTIFICATION_USER_ID` int NOT NULL,
  `3DMANAGER_NOTIFICATION_TYPE` int NOT NULL,
  PRIMARY KEY (`3DMANAGER_NOTIFICATION_ID`),
  KEY `FK_NOTIFICATION_USER_idx` (`3DMANAGER_NOTIFICATION_USER_ID`),
  KEY `FK_NOTIFICATION_TYPE_idx` (`3DMANAGER_NOTIFICATION_TYPE`),
  CONSTRAINT `FK_NOTIFICATION_TYPE` FOREIGN KEY (`3DMANAGER_NOTIFICATION_TYPE`) REFERENCES `3DMANAGER_C_TYPE_NOTIFICATION` (`3DMANAGER_C_TYPE_NOTIFICATION_ID`),
  CONSTRAINT `FK_NOTIFICATION_USER` FOREIGN KEY (`3DMANAGER_NOTIFICATION_USER_ID`) REFERENCES `3DMANAGER_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_3DPRINT` (
  `3DMANAGER_3DPRINT_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_3DPRINT_NAME` varchar(100) NOT NULL,
  `3DMANAGER_3DPRINT_STATE` int NOT NULL,
  `3DMANAGER_3DPRINT_IMPRESSION_TIME` int NOT NULL,
  `3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME` int NOT NULL,
  `3DMANAGER_3DPRINT_MATERIAL_CONSUMED` decimal(10,2) NOT NULL,
  `3DMANAGER_3DPRINT_GROUP_ID` int NOT NULL,
  `3DMANAGER_3DPRINT_PRINTER_ID` int NOT NULL,
  `3DMANAGER_3DPRINT_USER_ID` int NOT NULL,
  `3DMANAGER_3DPRINT_FILAMENT_ID` int NOT NULL,
  `3DMANAGER_3DPRINT_REGISTER_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `3DMANAGER_3DPRINT_DESCRIPTION` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`3DMANAGER_3DPRINT_ID`),
  KEY `FK_PRINT_USER_idx` (`3DMANAGER_3DPRINT_USER_ID`),
  KEY `FK_PRINT_FILAMENT_idx` (`3DMANAGER_3DPRINT_FILAMENT_ID`),
  KEY `FK_PRINT_GROUP_idx` (`3DMANAGER_3DPRINT_GROUP_ID`),
  KEY `FK_PRINT_PRINTER_idx` (`3DMANAGER_3DPRINT_PRINTER_ID`),
  KEY `FK_PRINT_STATE_idx` (`3DMANAGER_3DPRINT_STATE`),
  CONSTRAINT `FK_PRINT_FILAMENT` FOREIGN KEY (`3DMANAGER_3DPRINT_FILAMENT_ID`) REFERENCES `3DMANAGER_FILAMENT` (`3DMANAGER_FILAMENT_ID`),
  CONSTRAINT `FK_PRINT_GROUP` FOREIGN KEY (`3DMANAGER_3DPRINT_GROUP_ID`) REFERENCES `3DMANAGER_GROUP` (`3DMANAGER_GROUP_ID`),
  CONSTRAINT `FK_PRINT_PRINTER` FOREIGN KEY (`3DMANAGER_3DPRINT_PRINTER_ID`) REFERENCES `3DMANAGER_PRINTER` (`3DMANAGER_PRINTER_ID`),
  CONSTRAINT `FK_PRINT_STATE` FOREIGN KEY (`3DMANAGER_3DPRINT_STATE`) REFERENCES `3DMANAGER_C_STATE_PRINT` (`3DMANAGER_C_STATE_PRINT_ID`),
  CONSTRAINT `FK_PRINT_USER` FOREIGN KEY (`3DMANAGER_3DPRINT_USER_ID`) REFERENCES `3DMANAGER_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_COMMENT` (
  `3DMANAGER_COMMENT_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_COMMENT_COMMENT` varchar(500) NOT NULL,
  `3DMANAGER_COMMENT_USER_ID` int NOT NULL,
  `3DMANAGER_COMMENT_3DPRINT_ID` int NOT NULL,
  `3DMANAGER_COMMENT_REGISTER_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`3DMANAGER_COMMENT_ID`),
  KEY `FK_COMMENT_USER_idx` (`3DMANAGER_COMMENT_USER_ID`),
  KEY `FK_COMMENT_PRINT_idx` (`3DMANAGER_COMMENT_3DPRINT_ID`),
  CONSTRAINT `FK_COMMENT_PRINT` FOREIGN KEY (`3DMANAGER_COMMENT_3DPRINT_ID`) REFERENCES `3DMANAGER_3DPRINT` (`3DMANAGER_3DPRINT_ID`),
  CONSTRAINT `FK_COMMENT_USER` FOREIGN KEY (`3DMANAGER_COMMENT_USER_ID`) REFERENCES `3DMANAGER_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_SYSTEM_LOGS` (
  `LOG_ID` int NOT NULL AUTO_INCREMENT,
  `LOG_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PROCEDURE_NAME` varchar(100) NOT NULL,
  `ERROR_MESSAGE` varchar(500) NOT NULL,
  PRIMARY KEY (`LOG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- INSERT INITIAL DATA
INSERT INTO `3DMANAGER_C_STATE_PRINTER`
(`3DMANAGER_C_STATE_PRINTER_NAME`)
VALUES ('Activo'),('En mantenimiento'),('Fuera de servicio');

INSERT INTO `3DMANAGER_C_STATE_FILAMENT`
(`3DMANAGER_C_STATE_FILAMENT_NAME`)
VALUES ('Disponible'),('Agotado');

INSERT INTO `3DMANAGER_C_ROLES`
(`3DMANAGER_C_ROLES_NAME`)
VALUES ('Usuario-Base'),('Usuario-Manager'),('Usuario-Invitado');

INSERT INTO `3DMANAGER_C_TYPE_FILAMENT`
(`3DMANAGER_C_TYPE_FILAMENT_NAME`)
VALUES ('PLA'),('PLA +'),('ABS'),('PETG'),('TPU'),('TPE'),('Nylon'),('PC'),('ASA'),('POM'),('PLA-CF'),('Nylon-CF'),('PETG-CF'),('PVA'),('HIPS');

INSERT INTO `3DMANAGER_C_STATE_PRINT`
(`3DMANAGER_C_STATE_PRINT_NAME`)
VALUES ('Pendiente'),('Completada'),('No Completada');

INSERT INTO `3DMANAGER_C_TYPE_NOTIFICATION`
(`3DMANAGER_C_TYPE_NOTIFICATION_NAME`)
VALUES ('Aviso'),('Invitacion a grupo'),('Comentario en impresión');

INSERT INTO `3DMANAGER_USER`
(`USER_NAME`,`USER_PASSWORD`,`USER_EMAIL`, `USER_ROLE`, `USER_GROUP_ID`)
VALUES
('Invitado-Manager','AQAAAAIAAYagAAAAEHVWbM6i/sYDtYJHqlPW+ckpGV8Et/QzZcY8eA9BgwWfF7OwWNSd6cl+FXv1hjlAvg==','3dmanagerGuestManager@gmail.com',2,1),
('Invitado','AQAAAAIAAYagAAAAEDCPWazVXs+DAkPUp1LN0+PBiBgEwCTtNzcd1ywjabTt8wgq73xFhTe4n2Yr8/rH5A==','3dmanagerInvitado@gmail.com',2,1);

INSERT INTO `3DMANAGER_GROUP`
(`3DMANAGER_GROUP_NAME`,`3DMANAGER_GROUP_DESCRIPTION`,`3DMANAGER_USER_OWNER`)
VALUES
('Grupo Invitado', 'Este es un grupo del invitado, creado para proporcionar al usuario una vision de la app',1);		

INSERT INTO `3DMANAGER_FILAMENT`
(`3DMANAGER_FILAMENT_NAME`,
 `3DMANAGER_FILAMENT_DESCRIPTION`,
 `3DMANAGER_FILAMENT_STATE`,
 `3DMANAGER_FILAMENT_MATERIAL_LENGTH`,
 `3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH`,
 `3DMANAGER_FILAMENT_MATERIAL_THICKNESS`,
 `3DMANAGER_FILAMENT_TEMPERATURE`,
 `3DMANAGER_FILAMENT_COLOR`,
 `3DMANAGER_FILAMENT_GROUP_ID`,
 `3DMANAGER_FILAMENT_MATERIAL_TYPE`,
 `3DMANAGER_FILAMENT_WEIGHT`,
 `3DMANAGER_FILAMENT_COST`)
VALUES
('Filamento ELEGOO PLA','Bobina de color negro, compatible con la mayoría de impresoras. Comprada en amazon por rebaja',
 1,300.0000, 295.4200, 1.75, 195, '#000000', 1, 2, 1, 15.00),
('Filamento Blaco eSUN','Bobina de buena calidad, pero el material es muy útil para estructuras fuertes, no recomendable para detalles de alto nivel',
 1,325.000, 320.4200, 1.75, 205, '#ffffff', 1, 1, 1, 12.00),		
('SOLEYIN verde','Bobina especialmente útil para impresiones de alta velocidad. Compatible con mayoría de impresoras',
 1,300.000, 295.4200, 1.75, 205, '#7edd91', 1, 1, 1, 9.19);	
 		
INSERT INTO `3DMANAGER_PRINTER`
(`3DMANAGER_PRINTER_NAME`,
`3DMANAGER_PRINTER_MODEL`,
`3DMANAGER_PRINTER_STATE`,
`3DMANAGER_PRINTER_GROUP_ID`,
`3DMANAGER_PRINTER_DESCRIPTION`)
VALUES
('Impresora invitado 1','Creality Ender V1 SE',1,1,'Esta es la impresora 1 de invitado.'),
('Impresora invitado 2','Creality Ender V2 SE',2,1,'Esta es la impresora 2 de invitado.'),
('Impresora invitado 3','Creality Ender V3 SE',3,1,'Esta es la impresora 3 de invitado.')
;

INSERT INTO `3DMANAGER_3DPRINT`
(`3DMANAGER_3DPRINT_NAME`,
`3DMANAGER_3DPRINT_STATE`,
`3DMANAGER_3DPRINT_IMPRESSION_TIME`,
`3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME`,
`3DMANAGER_3DPRINT_MATERIAL_CONSUMED`,
`3DMANAGER_3DPRINT_GROUP_ID`,
`3DMANAGER_3DPRINT_PRINTER_ID`,
`3DMANAGER_3DPRINT_USER_ID`,
`3DMANAGER_3DPRINT_FILAMENT_ID`,
`3DMANAGER_3DPRINT_DESCRIPTION`)
VALUES
('Impresion 1',2,5184,4380,4.58,1,1,2,1,'Benchy test 1 con filamento 1'),
('Impresion 2',2,5184,4800,4.74,1,1,2,2,'Benchy test 2 con filamento 2'),
('Impresion 3',2,5184,5180,4.96,1,2,2,3,'Benchy test 3 con filamento 3')
;

-- STORED PROCEDURES
		
DELIMITER $$

CREATE PROCEDURE `3DMANAGER_pr_C_FILAMENT`(
    IN P_CD_GROUP INT,
    OUT CodigoError INT
)
BEGIN
    SELECT 
        3DMANAGER_FILAMENT_ID AS ID,
        3DMANAGER_FILAMENT_NAME AS DESCRIPTION
    FROM 3DMANAGER_FILAMENT
    WHERE P_CD_GROUP = 3DMANAGER_FILAMENT.`3DMANAGER_FILAMENT_GROUP_ID`
      AND 3DMANAGER_FILAMENT.`3DMANAGER_FILAMENT_STATE` = 1;
END$$

CREATE PROCEDURE `3DMANAGER_pr_C_FILAMENT_TYPE`()
BEGIN
    SELECT 
        `3DMANAGER_C_TYPE_FILAMENT_ID` AS ID,
        `3DMANAGER_C_TYPE_FILAMENT_NAME` AS DESCRIPTION
    FROM 3DMANAGER_C_TYPE_FILAMENT;
END$$

CREATE PROCEDURE `3DMANAGER_pr_C_PRINT_STATE`(
    OUT CodigoError INT
)
BEGIN
    SELECT 
        3DMANAGER_C_STATE_PRINT_ID AS ID,
        3DMANAGER_C_STATE_PRINT_NAME AS DESCRIPTION
    FROM 3DMANAGER_C_STATE_PRINT;
END$$

CREATE PROCEDURE `3DMANAGER_pr_C_PRINTER`(
    IN P_CD_GROUP INT,
    OUT CodigoError INT
)
BEGIN
    SELECT 
        3DMANAGER_PRINTER_ID AS ID,
        3DMANAGER_PRINTER_NAME AS DESCRIPTION
    FROM 3DMANAGER_PRINTER
    WHERE P_CD_GROUP = 3DMANAGER_PRINTER.`3DMANAGER_PRINTER_GROUP_ID`
      AND 3DMANAGER_PRINTER.`3DMANAGER_PRINTER_STATE` = 1;
END$$

CREATE PROCEDURE `3DMANAGER_pr_FILAMENT_LIST`(
    IN P_CD_GROUP INT,
    OUT CodigoError INT
)
BEGIN
    SELECT 
        `3DMANAGER_FILAMENT_ID` AS FILAMENT_ID,
        `3DMANAGER_FILAMENT_NAME` AS FILAMENT_NAME,
        ST.`3DMANAGER_C_STATE_FILAMENT_NAME` AS FILAMENT_STATE,
        `3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH` AS FILAMENT_LENGTH,
        `3DMANAGER_FILAMENT_COST` AS FILAMENT_COST
    FROM 3DMANAGER_FILAMENT 
    LEFT JOIN 3DMANAGER_C_STATE_FILAMENT ST 
        ON 3DMANAGER_FILAMENT_STATE = ST.`3DMANAGER_C_STATE_FILAMENT_ID`
    WHERE 3DMANAGER_FILAMENT_GROUP_ID = P_CD_GROUP;
END$$

CREATE PROCEDURE `3DMANAGER_pr_FILAMENT_POST`(
    IN P_GROUP_ID INT,
    IN P_FILAMENT_NAME VARCHAR(100),
    IN P_FILAMENT_TYPE INT,
    IN P_FILAMENT_WEIGHT INT,
    IN P_FILAMENT_COLOR VARCHAR(10),
    IN P_FILAMENT_TEMPERATURE INT,
    IN P_FILAMENT_THICKNESS FLOAT,
    IN P_FILAMENT_COST DECIMAL(10,2),
    IN P_FILAMENT_LENGHT INT,
    IN P_FILAMENT_DESCRIPTION VARCHAR(500),
    OUT CodigoError INT
)
BEGIN
    DECLARE NEW_ID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET CodigoError = -1;
    END;

    SET CodigoError = 0;
    START TRANSACTION;

    INSERT INTO 3DMANAGER_FILAMENT (
        3DMANAGER_FILAMENT_NAME,
        3DMANAGER_FILAMENT_DESCRIPTION,
        3DMANAGER_FILAMENT_STATE,
        3DMANAGER_FILAMENT_MATERIAL_LENGTH,
        3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH,
        3DMANAGER_FILAMENT_MATERIAL_THICKNESS,
        3DMANAGER_FILAMENT_TEMPERATURE,
        3DMANAGER_FILAMENT_COLOR,
        3DMANAGER_FILAMENT_GROUP_ID,
        3DMANAGER_FILAMENT_MATERIAL_TYPE,
        3DMANAGER_FILAMENT_WEIGHT,
        3DMANAGER_FILAMENT_COST
    ) VALUES (
        P_FILAMENT_NAME,
        P_FILAMENT_DESCRIPTION,
        1,
        P_FILAMENT_LENGHT,
        P_FILAMENT_LENGHT,
        P_FILAMENT_THICKNESS,
        P_FILAMENT_TEMPERATURE,
        P_FILAMENT_COLOR,
        P_GROUP_ID,
        P_FILAMENT_TYPE,
        P_FILAMENT_WEIGHT,
        P_FILAMENT_COST
    );

    SET NEW_ID = LAST_INSERT_ID();
    COMMIT;

    SELECT 3DMANAGER_FILAMENT_ID 
    FROM 3DMANAGER_FILAMENT 
    WHERE NEW_ID = 3DMANAGER_FILAMENT_ID;
END$$

CREATE PROCEDURE `3DMANAGER_pr_GROUP_ACCEPT_INVITATION`(
    IN P_CD_GROUP INT,
    IN P_CD_USER INT,
    IN P_IT_ACCEPTED BIT,
    OUT CodigoError INT
)
BEGIN
	
	DECLARE NEW_ID INT;
    DECLARE CONTINUE_OP BIT;
     -- Si hay un error SQL, se entra al handler, se hace rollback y se asigna el código -1
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET CodigoError = -1;
    END;
    
    SET CodigoError = 0;
	START TRANSACTION;
		
		IF( (SELECT USER_GROUP_ID FROM 3DMANAGER_USER WHERE USER_ID = P_CD_USER) IS NULL AND
        EXISTS( SELECT 1 FROM 3DMANAGER_INVITATIONS I WHERE I.`3DMANAGER_INVITATIONS_USER_ID` = P_CD_USER AND I.`3DMANAGER_INVITATIONS_GROUP_ID` = P_CD_GROUP) )
		THEN
			 IF (P_IT_ACCEPTED)
             THEN
				UPDATE 3DMANAGER_USER SET USER_GROUP_ID = P_CD_GROUP,USER_ROLE = 1 WHERE USER_ID = P_CD_USER ;
				DELETE FROM 3DMANAGER_INVITATIONS WHERE P_CD_USER = `3DMANAGER_INVITATIONS_USER_ID`;
			 ELSE
				DELETE FROM 3DMANAGER_INVITATIONS WHERE P_CD_USER = `3DMANAGER_INVITATIONS_USER_ID` AND `3DMANAGER_INVITATIONS_GROUP_ID` = P_CD_GROUP;
			END IF;
        END IF;	
    COMMIT;    
	SELECT USER_GROUP_ID FROM 3DMANAGER_USER WHERE USER_ID = P_CD_USER;
END$$

CREATE PROCEDURE `3DMANAGER_pr_GROUP_INVITATIONS`(
	IN P_CD_USER INT
)
BEGIN
	SELECT 
		U.USER_NAME AS 'USER_OWNER',
        G.`3DMANAGER_GROUP_ID` as 'GROUP_ID',
        G.`3DMANAGER_GROUP_NAME` as 'GROUP_NAME',
        G.`3DMANAGER_GROUP_DESCRIPTION` as 'GROUP_DESCRIPTION'
    FROM 3DMANAGER_INVITATIONS I
    LEFT JOIN 3DMANAGER_GROUP G ON G.`3DMANAGER_GROUP_ID` = I.`3DMANAGER_INVITATIONS_GROUP_ID`
    LEFT JOIN 3DMANAGER_USER U ON U.USER_ID = G.`3DMANAGER_USER_OWNER`
    WHERE P_CD_USER = I.`3DMANAGER_INVITATIONS_USER_ID`;
END$$

CREATE PROCEDURE `3DMANAGER_pr_GROUP_POST`(
    IN P_CD_USER_ID INT,
    IN P_DS_GROUP_NAME VARCHAR(100),
    IN P_DS_GROUP_DESCRIPTION VARCHAR(500),
    OUT CodigoError INT
)
BEGIN

	-- Si hay un error SQL, se entra al handler, se hace rollback y se asigna el código -1
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET CodigoError = -1;
    END;
    SET CodigoError = 0;
	START TRANSACTION;
    IF EXISTS (
        SELECT 1 FROM 3DMANAGER_GROUP WHERE 3DMANAGER_GROUP_NAME = P_DS_GROUP_NAME
    ) THEN
        SET CodigoError = 4091;
    ELSE
        INSERT INTO 3DMANAGER_GROUP (3DMANAGER_GROUP_NAME,3DMANAGER_GROUP_DESCRIPTION)
        VALUES (P_DS_GROUP_NAME, P_DS_GROUP_DESCRIPTION);
        
        UPDATE 3DMANAGER_USER 
			SET USER_ROLE = 2,
				USER_GROUP_ID = (SELECT 3DMANAGER_GROUP_ID FROM 3DMANAGER_GROUP WHERE P_DS_GROUP_NAME = 3DMANAGER_GROUP_NAME)
			WHERE USER_ID = P_CD_USER_ID;
        
        SELECT 3DMANAGER_GROUP_NAME FROM 3DMANAGER_GROUP WHERE P_DS_GROUP_NAME = 3DMANAGER_GROUP_NAME;
    END IF;
    
    COMMIT;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINT_LIST`(
    IN P_CD_GROUP INT,
    OUT CodigoError INT
)
BEGIN
	SELECT 
		`3DMANAGER_3DPRINT_ID` AS PRINT_ID,
        `3DMANAGER_3DPRINT_NAME` AS PRINT_NAME,
        `USER_NAME` AS PRINT_USER,
        `3DMANAGER_3DPRINT_REGISTER_DATE` AS PRINT_DATE,
        `3DMANAGER_3DPRINT_IMPRESSION_TIME` AS PRINT_TIME,
        `3DMANAGER_3DPRINT_MATERIAL_CONSUMED` AS PRINT_FILAMENT_USED
    FROM 3DMANAGER_3DPRINT 
    LEFT JOIN 3DMANAGER_USER ON `3DMANAGER_3DPRINT_USER_ID` = `USER_ID`
    WHERE 3DMANAGER_3DPRINT_GROUP_ID = P_CD_GROUP  ;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINT_POST`(
    IN P_GROUP_ID INT,
    IN P_USER_ID INT,
    IN P_PRINT_NAME VARCHAR(100),
    IN P_PRINT_STATE INT,
    IN P_PRINT_PRINTER_ID INT,
    IN P_PRINT_FILAMENT_ID INT,
    IN P_PRINT_DESCRIPTION VARCHAR(500),
    IN P_PRINT_TIME INT,
    IN P_PRINT_FILAMENT_USED DECIMAL(10,2),
    IN P_PRINT_REAL_TIME INT,
    OUT CodigoError INT
)
BEGIN
    DECLARE NEW_ID INT;
    DECLARE CURRENT_FILAMENT_LENGTH DECIMAL(10,2);
    DECLARE v_err_msg TEXT;
    DECLARE NEW_STATE INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO 3DMANAGER_SYSTEM_LOGS(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_PRINT_POST', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;
    
    SET CodigoError = 0;
    START TRANSACTION;

    SELECT `3DMANAGER_FILAMENT`.`3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH`
    INTO CURRENT_FILAMENT_LENGTH
    FROM 3DMANAGER_FILAMENT
    WHERE `3DMANAGER_FILAMENT`.`3DMANAGER_FILAMENT_ID` = P_PRINT_FILAMENT_ID;

    SET CURRENT_FILAMENT_LENGTH = CURRENT_FILAMENT_LENGTH - P_PRINT_FILAMENT_USED;
	SET  NEW_STATE = CASE WHEN CURRENT_FILAMENT_LENGTH <= 0 THEN 2 ELSE 1 END;
    
    INSERT INTO 3DMANAGER_3DPRINT (
        3DMANAGER_3DPRINT_NAME,
        3DMANAGER_3DPRINT_DESCRIPTION,
        3DMANAGER_3DPRINT_STATE,
        3DMANAGER_3DPRINT_IMPRESSION_TIME,
        3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME,
        3DMANAGER_3DPRINT_GROUP_ID,
        3DMANAGER_3DPRINT_FILAMENT_ID,
        3DMANAGER_3DPRINT_USER_ID,
        3DMANAGER_3DPRINT_PRINTER_ID,
        3DMANAGER_3DPRINT_MATERIAL_CONSUMED 
    ) VALUES (
        P_PRINT_NAME,
        P_PRINT_DESCRIPTION,
        P_PRINT_STATE,
        P_PRINT_TIME,
        P_PRINT_REAL_TIME,
        P_GROUP_ID,
        P_PRINT_FILAMENT_ID,
        P_USER_ID,
        P_PRINT_PRINTER_ID,
        P_PRINT_FILAMENT_USED
    );

    SET NEW_ID = LAST_INSERT_ID();

    UPDATE 3DMANAGER_FILAMENT 
    SET `3DMANAGER_FILAMENT`.`3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH` = CURRENT_FILAMENT_LENGTH,
		`3DMANAGER_FILAMENT`.`3DMANAGER_FILAMENT_STATE` = NEW_STATE
    WHERE `3DMANAGER_FILAMENT_ID` = P_PRINT_FILAMENT_ID;
	
    COMMIT;

    SELECT NEW_ID AS PRINT_ID;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINTER_LIST`(
    IN P_CD_GROUP INT,
    OUT CodigoError INT
)
BEGIN
	SELECT 
		`3DMANAGER_PRINTER_ID` AS PRINTER_ID,
        `3DMANAGER_PRINTER_NAME` AS PRINTER_NAME,
        `3DMANAGER_PRINTER_MODEL` AS PRINTER_MODEL,
        `3DMANAGER_PRINTER_DESCRIPTION` AS PRINTER_DESCRIPTION,
        `3DMANAGER_PRINTER_STATE` AS PRINTER_STATE_ID,
        `3DMANAGER_C_STATE_PRINTER_NAME` AS PRINTER_STATE_NAME,
        `3DMANAGER_PRINTER_IMAGE_URL` AS FILE_URL,
        `3DMANAGER_PRINTER_IMAGE_KEY` AS FILE_KEY
    FROM 3DMANAGER_PRINTER 
    LEFT JOIN 3DMANAGER_C_STATE_PRINTER ON `3DMANAGER_C_STATE_PRINTER_ID` = `3DMANAGER_PRINTER_STATE`
    WHERE 3DMANAGER_PRINTER_GROUP_ID = P_CD_GROUP  ;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINTER_POST`(
    IN P_GROUP_ID INT,
    IN P_PRINTER_NAME VARCHAR(100),
    IN P_PRINTER_MODEL VARCHAR(100),
    IN P_PRINTER_DESCRIPTION VARCHAR(500),
    OUT CodigoError INT
)
BEGIN
	DECLARE NEW_ID INT;
    
     -- Si hay un error SQL, se entra al handler, se hace rollback y se asigna el código -1
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET CodigoError = -1;
    END;
    
    SET CodigoError = 0;
    IF EXISTS(SELECT 1 FROM 3DMANAGER_PRINTER WHERE `3DMANAGER_PRINTER_NAME` = P_PRINTER_NAME AND `3DMANAGER_PRINTER_GROUP_ID` = P_GROUP_ID )
    THEN
		SET CodigoError = 1;
	ELSE
		START TRANSACTION;
		INSERT INTO 3DMANAGER_PRINTER (
			3DMANAGER_PRINTER_NAME,
			3DMANAGER_PRINTER_DESCRIPTION,
			3DMANAGER_PRINTER_STATE,
			3DMANAGER_PRINTER_MODEL,
			3DMANAGER_PRINTER_GROUP_ID
		) VALUES (
			P_PRINTER_NAME,
			P_PRINTER_DESCRIPTION,
			1,
			P_PRINTER_MODEL,
			P_GROUP_ID
		);
    
		SET NEW_ID = LAST_INSERT_ID();
		COMMIT;    
		SELECT 3DMANAGER_PRINTER_ID FROM 3DMANAGER_PRINTER WHERE NEW_ID = 3DMANAGER_PRINTER_ID;
	END IF;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINTER_POST`(
    IN P_GROUP_ID INT,
    IN P_PRINTER_NAME VARCHAR(100),
    IN P_PRINTER_MODEL VARCHAR(100),
    IN P_PRINTER_DESCRIPTION VARCHAR(500),
    OUT CodigoError INT
)
BEGIN
	DECLARE NEW_ID INT;
    
     -- Si hay un error SQL, se entra al handler, se hace rollback y se asigna el código -1
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET CodigoError = -1;
    END;
    
    SET CodigoError = 0;
    IF EXISTS(SELECT 1 FROM 3DMANAGER_PRINTER WHERE `3DMANAGER_PRINTER_NAME` = P_PRINTER_NAME AND `3DMANAGER_PRINTER_GROUP_ID` = P_GROUP_ID )
    THEN
		SET CodigoError = 1;
	ELSE
		START TRANSACTION;
		INSERT INTO 3DMANAGER_PRINTER (
			3DMANAGER_PRINTER_NAME,
			3DMANAGER_PRINTER_DESCRIPTION,
			3DMANAGER_PRINTER_STATE,
			3DMANAGER_PRINTER_MODEL,
			3DMANAGER_PRINTER_GROUP_ID
		) VALUES (
			P_PRINTER_NAME,
			P_PRINTER_DESCRIPTION,
			1,
			P_PRINTER_MODEL,
			P_GROUP_ID
		);
    
		SET NEW_ID = LAST_INSERT_ID();
		COMMIT;    
		SELECT 3DMANAGER_PRINTER_ID FROM 3DMANAGER_PRINTER WHERE NEW_ID = 3DMANAGER_PRINTER_ID;
	END IF;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINTER_POST_IMAGE`(
    IN P_PRINTER_ID INT,
    IN P_KEY VARCHAR(255),
    IN P_URL VARCHAR(255),
    OUT CodigoError INT
)
BEGIN
     -- Si hay un error SQL, se entra al handler, se hace rollback y se asigna el código -1
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET CodigoError = -1;
    END;
    
    SET CodigoError = 0;
    
	START TRANSACTION;
	UPDATE 3DMANAGER_PRINTER 
    SET `3DMANAGER_PRINTER_IMAGE_URL` = P_URL,
		`3DMANAGER_PRINTER_IMAGE_KEY` = P_KEY
        WHERE `3DMANAGER_PRINTER_ID` = P_PRINTER_ID;	
	COMMIT;    
		SELECT 3DMANAGER_PRINTER_ID FROM 3DMANAGER_PRINTER WHERE P_PRINTER_ID = 3DMANAGER_PRINTER_ID;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_INVITATION`(
    IN P_CD_GROUP INT,
    IN P_CD_USER INT
)
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM 3DMANAGER_INVITATIONS 
        WHERE `3DMANAGER_INVITATIONS_USER_ID` = P_CD_USER 
          AND `3DMANAGER_INVITATIONS_GROUP_ID` = P_CD_GROUP
    ) THEN
        INSERT INTO 3DMANAGER_INVITATIONS (
            3DMANAGER_INVITATIONS_USER_ID,
            3DMANAGER_INVITATIONS_GROUP_ID
        )
        VALUES (P_CD_USER, P_CD_GROUP);
    END IF;
	
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_INVITATION_LIST`()
BEGIN
	SELECT
		USER_ID,
        USER_NAME
    FROM 3DMANAGER_USER 
    WHERE USER_GROUP_ID IS NULL
    ;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_LIST`(
    IN P_CD_GROUP INT,
    OUT CodigoError INT
)
BEGIN
	SELECT 
		USER_ID,
        USER_NAME,
        IFNULL((SELECT SUM(`3DMANAGER_3DPRINT_IMPRESSION_TIME`) FROM 3DMANAGER_3DPRINT WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP AND `3DMANAGER_3DPRINT_USER_ID` = USER_ID ),0) AS USER_HOURS,
        (SELECT COUNT(*) FROM 3DMANAGER_3DPRINT WHERE 3DMANAGER_3DPRINT_GROUP_ID = P_CD_GROUP AND `3DMANAGER_3DPRINT_USER_ID` = USER_ID ) AS NUMBER_PRINTS
    FROM 3DMANAGER_USER
    WHERE USER_GROUP_ID = P_CD_GROUP ;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_LOGIN`(
    IN P_DS_USER_NAME VARCHAR(100)
)
BEGIN
    SELECT 
		u.USER_ID,
        u.USER_NAME,
        u.USER_PASSWORD,
        u.USER_EMAIL,
        u.USER_GROUP_ID,
        r.`3DMANAGER_C_ROLES_NAME` AS USER_ROLE,
        g.`3DMANAGER_GROUP_NAME` AS GROUP_NAME
        
    FROM `3DMANAGER_USER` AS u
    LEFT JOIN `3DMANAGER_C_ROLES` AS r 
        ON u.USER_ROLE = r.`3DMANAGER_C_ROLES_ID`
	LEFT JOIN `3DMANAGER_GROUP` AS g
		ON G.`3DMANAGER_GROUP_ID` = u.USER_GROUP_ID 
    WHERE u.USER_NAME = P_DS_USER_NAME;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_POST`(
    IN P_DS_USER_NAME VARCHAR(100),
    IN P_DS_USER_PASSWORD VARCHAR(255),
    IN P_DS_USER_EMAIL VARCHAR(100),
    OUT CodigoError INT
)
BEGIN

	-- Si hay un error SQL, se entra al handler, se hace rollback y se asigna el código -1
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET CodigoError = -1;
    END;
    
    SET CodigoError = 0;
	START TRANSACTION;
		IF EXISTS (
			SELECT 1 FROM 3DMANAGER_USER WHERE USER_NAME = P_DS_USER_NAME
		) THEN
			SET CodigoError = 4091;
		ELSEIF EXISTS (
			SELECT 1 FROM 3DMANAGER_USER WHERE USER_EMAIL = P_DS_USER_EMAIL
		) THEN
			SET CodigoError = 4092;
		ELSE
			INSERT INTO 3DMANAGER_USER (USER_NAME,USER_PASSWORD, USER_EMAIL)
			VALUES (P_DS_USER_NAME, P_DS_USER_PASSWORD, P_DS_USER_EMAIL);
			
			SELECT USER_NAME FROM 3DMANAGER_USER WHERE P_DS_USER_NAME = USER_NAME;
		END IF;
	COMMIT;
END$$

DELIMITER ;

