-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS 3dmanager; USE 3dmanager;

-- CREATE TABLES
CREATE TABLE `3DMANAGER_C_ROLES` (
  `3DMANAGER_C_ROLES_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_C_ROLES_NAME` varchar(30) NOT NULL,
<<<<<<< HEAD
  PRIMARY KEY (`3DMANAGER_C_ROLES_ID`)
=======
  PRIMARY KEY (`3DMANAGER_C_ROLES_ID`
>>>>>>> release/0.2.0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_C_STATE_FILAMENT` (
  `3DMANAGER_C_STATE_FILAMENT_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_C_STATE_FILAMENT_NAME` varchar(50) NOT NULL,
  PRIMARY KEY (`3DMANAGER_C_STATE_FILAMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_C_STATE_PRINT` (
  `3DMANAGER_C_STATE_PRINT_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_C_STATE_PRINT_NAME` varchar(50) NOT NULL,
  PRIMARY KEY (`3DMANAGER_C_STATE_PRINT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_C_STATE_PRINTER` (
  `3DMANAGER_C_STATE_PRINTER_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_C_STATE_PRINTER_NAME` varchar(50) NOT NULL,
  PRIMARY KEY (`3DMANAGER_C_STATE_PRINTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_C_TYPE_FILAMENT` (
  `3DMANAGER_C_TYPE_FILAMENT_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_C_TYPE_FILAMENT_NAME` varchar(30) NOT NULL,
  PRIMARY KEY (`3DMANAGER_C_TYPE_FILAMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_C_TYPE_NOTIFICATION` (
  `3DMANAGER_C_TYPE_NOTIFICATION_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_C_TYPE_NOTIFICATION_NAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`3DMANAGER_C_TYPE_NOTIFICATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

<<<<<<< HEAD

=======
>>>>>>> release/0.2.0
CREATE TABLE `3DMANAGER_GROUP` (
  `3DMANAGER_GROUP_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_GROUP_NAME` varchar(100) NOT NULL,
  `3DMANAGER_GROUP_DESCRIPTION` varchar(500) DEFAULT NULL,
  `3DMANAGER_PRINTER_REGISTER_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
<<<<<<< HEAD
  `3DMANAGER_USER_OWNER` int NOT NULL,
=======
  `3DMANAGER_USER_OWNER` int NOT NULL DEFAULT '1',
>>>>>>> release/0.2.0
  PRIMARY KEY (`3DMANAGER_GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_USER` (
  `USER_ID` int NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(100) NOT NULL,
  `USER_PASSWORD` varchar(255) NOT NULL,
  `USER_EMAIL` varchar(100) NOT NULL,
  `USER_ROLE` int DEFAULT NULL,
  `USER_GROUP_ID` int DEFAULT NULL,
  `USER_PHOTO_URL` varchar(255) DEFAULT NULL,
  `USER_REGISTER_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
<<<<<<< HEAD
=======
  `USER_IMAGE_URL` varchar(255) DEFAULT NULL,
  `USER_IMAGE_KEY` varchar(255) DEFAULT NULL,
>>>>>>> release/0.2.0
  PRIMARY KEY (`USER_ID`),
  KEY `FK_USER_GROUP_idx` (`USER_GROUP_ID`),
  KEY `FK_USER_ROLE_idx` (`USER_ROLE`),
  CONSTRAINT `FK_USER_GROUP` FOREIGN KEY (`USER_GROUP_ID`) REFERENCES `3DMANAGER_GROUP` (`3DMANAGER_GROUP_ID`),
  CONSTRAINT `FK_USER_ROLE` FOREIGN KEY (`USER_ROLE`) REFERENCES `3DMANAGER_C_ROLES` (`3DMANAGER_C_ROLES_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_FILAMENT` (
  `3DMANAGER_FILAMENT_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_FILAMENT_NAME` varchar(100) NOT NULL,
  `3DMANAGER_FILAMENT_DESCRIPTION` varchar(500) DEFAULT NULL,
  `3DMANAGER_FILAMENT_STATE` int NOT NULL,
  `3DMANAGER_FILAMENT_MATERIAL_LENGTH` decimal(10,4) NOT NULL,
  `3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH` decimal(10,4) NOT NULL,
<<<<<<< HEAD
  `3DMANAGER_FILAMENT_MATERIAL_THICKNESS` float DEFAULT NULL,
  `3DMANAGER_FILAMENT_TEMPERATURE` int DEFAULT NULL,
  `3DMANAGER_FILAMENT_COLOR` varchar(10) DEFAULT NULL,
  `3DMANAGER_FILAMENT_GROUP_ID` int NOT NULL,
  `3DMANAGER_FILAMENT_MATERIAL_TYPE` int NOT NULL,
  `3DMANAGER_FILAMENT_REGISTER_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `3DMANAGER_FILAMENT_WEIGHT` int DEFAULT NULL,
  `3DMANAGER_FILAMENT_COST` decimal(10,2) DEFAULT NULL,
=======
  `3DMANAGER_FILAMENT_MATERIAL_THICKNESS` float NOT NULL,
  `3DMANAGER_FILAMENT_TEMPERATURE` int NOT NULL,
  `3DMANAGER_FILAMENT_COLOR` varchar(10) NOT NULL,
  `3DMANAGER_FILAMENT_GROUP_ID` int NOT NULL,
  `3DMANAGER_FILAMENT_MATERIAL_TYPE` int NOT NULL,
  `3DMANAGER_FILAMENT_REGISTER_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `3DMANAGER_FILAMENT_WEIGHT` int NOT NULL,
  `3DMANAGER_FILAMENT_COST` decimal(10,2) NOT NULL,
  `3DMANAGER_FILAMENT_IMAGE_URL` varchar(255)  DEFAULT NULL,
  `3DMANAGER_FILAMENT_IMAGE_KEY` varchar(255)  DEFAULT NULL,
  `3DMANAGER_FILAMENT_COST_PER_METER` decimal(10,4) GENERATED ALWAYS AS ((`3DMANAGER_FILAMENT_COST` / nullif(`3DMANAGER_FILAMENT_MATERIAL_LENGTH`,0))) STORED,
  `3DMANAGER_FILAMENT_DELETED` bit(1) DEFAULT b'0',
>>>>>>> release/0.2.0
  PRIMARY KEY (`3DMANAGER_FILAMENT_ID`),
  KEY `FK_FILAMENT_STATE_idx` (`3DMANAGER_FILAMENT_STATE`),
  KEY `FK_FILAMENT_MATERIAL_idx` (`3DMANAGER_FILAMENT_MATERIAL_TYPE`),
  KEY `FK_FILAMENT_GROUP_idx` (`3DMANAGER_FILAMENT_GROUP_ID`),
  CONSTRAINT `FK_FILAMENT_GROUP` FOREIGN KEY (`3DMANAGER_FILAMENT_GROUP_ID`) REFERENCES `3DMANAGER_GROUP` (`3DMANAGER_GROUP_ID`),
  CONSTRAINT `FK_FILAMENT_MATERIAL` FOREIGN KEY (`3DMANAGER_FILAMENT_MATERIAL_TYPE`) REFERENCES `3DMANAGER_C_TYPE_FILAMENT` (`3DMANAGER_C_TYPE_FILAMENT_ID`),
  CONSTRAINT `FK_FILAMENT_STATE` FOREIGN KEY (`3DMANAGER_FILAMENT_STATE`) REFERENCES `3DMANAGER_C_STATE_FILAMENT` (`3DMANAGER_C_STATE_FILAMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

<<<<<<< HEAD
=======

>>>>>>> release/0.2.0
CREATE TABLE `3DMANAGER_PRINTER` (
  `3DMANAGER_PRINTER_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_PRINTER_NAME` varchar(100) NOT NULL,
  `3DMANAGER_PRINTER_MODEL` varchar(100) DEFAULT NULL,
  `3DMANAGER_PRINTER_TIME_VARIATION` float DEFAULT NULL,
  `3DMANAGER_PRINTER_STATE` int DEFAULT NULL,
  `3DMANAGER_PRINTER_GROUP_ID` int DEFAULT NULL,
  `3DMANAGER_PRINTER_REGISTER_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `3DMANAGER_PRINTER_DESCRIPTION` varchar(100) DEFAULT NULL,
  `3DMANAGER_PRINTER_IMAGE_URL` varchar(255) DEFAULT NULL,
  `3DMANAGER_PRINTER_IMAGE_KEY` varchar(255) DEFAULT NULL,
<<<<<<< HEAD
=======
  `3DMANAGER_PRINTER_DELETED` bit(1) DEFAULT b'0',
>>>>>>> release/0.2.0
  PRIMARY KEY (`3DMANAGER_PRINTER_ID`),
  KEY `FK_PRINTER_GROUP_idx` (`3DMANAGER_PRINTER_GROUP_ID`),
  KEY `FK_PRINTER_STATE_idx` (`3DMANAGER_PRINTER_STATE`),
  CONSTRAINT `FK_PRINTER_GROUP` FOREIGN KEY (`3DMANAGER_PRINTER_GROUP_ID`) REFERENCES `3DMANAGER_GROUP` (`3DMANAGER_GROUP_ID`),
  CONSTRAINT `FK_PRINTER_STATE` FOREIGN KEY (`3DMANAGER_PRINTER_STATE`) REFERENCES `3DMANAGER_C_STATE_PRINTER` (`3DMANAGER_C_STATE_PRINTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `3DMANAGER_INVITATIONS` (
  `3DMANAGER_INVITATIONS_USER_ID` int NOT NULL,
  `3DMANAGER_INVITATIONS_GROUP_ID` int NOT NULL,
  PRIMARY KEY (`3DMANAGER_INVITATIONS_GROUP_ID`,`3DMANAGER_INVITATIONS_USER_ID`),
  KEY `FK_INVITATION_USER` (`3DMANAGER_INVITATIONS_USER_ID`),
  CONSTRAINT `FK_INVITATION_GROUP` FOREIGN KEY (`3DMANAGER_INVITATIONS_GROUP_ID`) REFERENCES `3DMANAGER_GROUP` (`3DMANAGER_GROUP_ID`),
  CONSTRAINT `FK_INVITATION_USER` FOREIGN KEY (`3DMANAGER_INVITATIONS_USER_ID`) REFERENCES `3DMANAGER_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_NOTIFICATION` (
  `3DMANAGER_NOTIFICATION_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_NOTIFICATION_IT_READ` bit(1) NOT NULL,
  `3DMANAGER_NOTIFICATION_MESSAGE` varchar(500) NOT NULL,
  `3DMANAGER_NOTIFICATION_REGISTER_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `3DMANAGER_NOTIFICATION_USER_ID` int NOT NULL,
  `3DMANAGER_NOTIFICATION_TYPE` int NOT NULL,
  PRIMARY KEY (`3DMANAGER_NOTIFICATION_ID`),
  KEY `FK_NOTIFICATION_USER_idx` (`3DMANAGER_NOTIFICATION_USER_ID`),
  KEY `FK_NOTIFICATION_TYPE_idx` (`3DMANAGER_NOTIFICATION_TYPE`),
  CONSTRAINT `FK_NOTIFICATION_TYPE` FOREIGN KEY (`3DMANAGER_NOTIFICATION_TYPE`) REFERENCES `3DMANAGER_C_TYPE_NOTIFICATION` (`3DMANAGER_C_TYPE_NOTIFICATION_ID`),
  CONSTRAINT `FK_NOTIFICATION_USER` FOREIGN KEY (`3DMANAGER_NOTIFICATION_USER_ID`) REFERENCES `3DMANAGER_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_3DPRINT` (
  `3DMANAGER_3DPRINT_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_3DPRINT_NAME` varchar(100) NOT NULL,
  `3DMANAGER_3DPRINT_STATE` int NOT NULL,
  `3DMANAGER_3DPRINT_IMPRESSION_TIME` int NOT NULL,
  `3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME` int NOT NULL,
  `3DMANAGER_3DPRINT_MATERIAL_CONSUMED` decimal(10,2) NOT NULL,
  `3DMANAGER_3DPRINT_GROUP_ID` int NOT NULL,
  `3DMANAGER_3DPRINT_PRINTER_ID` int NOT NULL,
  `3DMANAGER_3DPRINT_USER_ID` int NOT NULL,
  `3DMANAGER_3DPRINT_FILAMENT_ID` int NOT NULL,
  `3DMANAGER_3DPRINT_REGISTER_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `3DMANAGER_3DPRINT_DESCRIPTION` varchar(500) DEFAULT NULL,
<<<<<<< HEAD
=======
  `3DMANAGER_3DPRINT_IMAGE_KEY` varchar(255) DEFAULT NULL,
  `3DMANAGER_3DPRINT_IMAGE_URL` varchar(255) DEFAULT NULL,
  `3DMANAGER_3DPRINT_DELETED` bit(1) NOT NULL DEFAULT b'0',
>>>>>>> release/0.2.0
  PRIMARY KEY (`3DMANAGER_3DPRINT_ID`),
  KEY `FK_PRINT_USER_idx` (`3DMANAGER_3DPRINT_USER_ID`),
  KEY `FK_PRINT_FILAMENT_idx` (`3DMANAGER_3DPRINT_FILAMENT_ID`),
  KEY `FK_PRINT_GROUP_idx` (`3DMANAGER_3DPRINT_GROUP_ID`),
  KEY `FK_PRINT_PRINTER_idx` (`3DMANAGER_3DPRINT_PRINTER_ID`),
  KEY `FK_PRINT_STATE_idx` (`3DMANAGER_3DPRINT_STATE`),
  CONSTRAINT `FK_PRINT_FILAMENT` FOREIGN KEY (`3DMANAGER_3DPRINT_FILAMENT_ID`) REFERENCES `3DMANAGER_FILAMENT` (`3DMANAGER_FILAMENT_ID`),
  CONSTRAINT `FK_PRINT_GROUP` FOREIGN KEY (`3DMANAGER_3DPRINT_GROUP_ID`) REFERENCES `3DMANAGER_GROUP` (`3DMANAGER_GROUP_ID`),
  CONSTRAINT `FK_PRINT_PRINTER` FOREIGN KEY (`3DMANAGER_3DPRINT_PRINTER_ID`) REFERENCES `3DMANAGER_PRINTER` (`3DMANAGER_PRINTER_ID`),
  CONSTRAINT `FK_PRINT_STATE` FOREIGN KEY (`3DMANAGER_3DPRINT_STATE`) REFERENCES `3DMANAGER_C_STATE_PRINT` (`3DMANAGER_C_STATE_PRINT_ID`),
  CONSTRAINT `FK_PRINT_USER` FOREIGN KEY (`3DMANAGER_3DPRINT_USER_ID`) REFERENCES `3DMANAGER_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_COMMENT` (
  `3DMANAGER_COMMENT_ID` int NOT NULL AUTO_INCREMENT,
  `3DMANAGER_COMMENT_COMMENT` varchar(500) NOT NULL,
  `3DMANAGER_COMMENT_USER_ID` int NOT NULL,
  `3DMANAGER_COMMENT_3DPRINT_ID` int NOT NULL,
  `3DMANAGER_COMMENT_REGISTER_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`3DMANAGER_COMMENT_ID`),
  KEY `FK_COMMENT_USER_idx` (`3DMANAGER_COMMENT_USER_ID`),
  KEY `FK_COMMENT_PRINT_idx` (`3DMANAGER_COMMENT_3DPRINT_ID`),
  CONSTRAINT `FK_COMMENT_PRINT` FOREIGN KEY (`3DMANAGER_COMMENT_3DPRINT_ID`) REFERENCES `3DMANAGER_3DPRINT` (`3DMANAGER_3DPRINT_ID`),
  CONSTRAINT `FK_COMMENT_USER` FOREIGN KEY (`3DMANAGER_COMMENT_USER_ID`) REFERENCES `3DMANAGER_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `3DMANAGER_SYSTEM_LOGS` (
  `LOG_ID` int NOT NULL AUTO_INCREMENT,
  `LOG_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PROCEDURE_NAME` varchar(100) NOT NULL,
  `ERROR_MESSAGE` varchar(500) NOT NULL,
  PRIMARY KEY (`LOG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- INSERT INITIAL DATA
INSERT INTO `3DMANAGER_C_STATE_PRINTER`
(`3DMANAGER_C_STATE_PRINTER_NAME`)
VALUES ('Activo'),('En mantenimiento'),('Fuera de servicio');

INSERT INTO `3DMANAGER_C_STATE_FILAMENT`
(`3DMANAGER_C_STATE_FILAMENT_NAME`)
VALUES ('Disponible'),('Agotado');

INSERT INTO `3DMANAGER_C_ROLES`
(`3DMANAGER_C_ROLES_NAME`)
VALUES ('Usuario-Base'),('Usuario-Manager'),('Usuario-Invitado');

INSERT INTO `3DMANAGER_C_TYPE_FILAMENT`
(`3DMANAGER_C_TYPE_FILAMENT_NAME`)
VALUES ('PLA'),('PLA +'),('ABS'),('PETG'),('TPU'),('TPE'),('Nylon'),('PC'),('ASA'),('POM'),('PLA-CF'),('Nylon-CF'),('PETG-CF'),('PVA'),('HIPS');

INSERT INTO `3DMANAGER_C_STATE_PRINT`
(`3DMANAGER_C_STATE_PRINT_NAME`)
<<<<<<< HEAD
VALUES ('Pendiente'),('Completada'),('No Completada');
=======
VALUES ('Completada'),('No Completada');
>>>>>>> release/0.2.0

INSERT INTO `3DMANAGER_C_TYPE_NOTIFICATION`
(`3DMANAGER_C_TYPE_NOTIFICATION_NAME`)
VALUES ('Aviso'),('Invitacion a grupo'),('Comentario en impresión');

INSERT INTO `3DMANAGER_GROUP`
(`3DMANAGER_GROUP_NAME`,`3DMANAGER_GROUP_DESCRIPTION`,`3DMANAGER_USER_OWNER`)
VALUES
('Grupo Invitado', 'Este es un grupo del invitado, creado para proporcionar al usuario una vision de la app',1);		

INSERT INTO `3DMANAGER_USER`
(`USER_NAME`,`USER_PASSWORD`,`USER_EMAIL`, `USER_ROLE`, `USER_GROUP_ID`)
VALUES
('Invitado-Manager','AQAAAAIAAYagAAAAEHVWbM6i/sYDtYJHqlPW+ckpGV8Et/QzZcY8eA9BgwWfF7OwWNSd6cl+FXv1hjlAvg==','3dmanagerGuestManager@gmail.com',2,1),
('Invitado','AQAAAAIAAYagAAAAEDCPWazVXs+DAkPUp1LN0+PBiBgEwCTtNzcd1ywjabTt8wgq73xFhTe4n2Yr8/rH5A==','3dmanagerInvitado@gmail.com',3,1);

INSERT INTO `3DMANAGER_FILAMENT`
(`3DMANAGER_FILAMENT_NAME`,
 `3DMANAGER_FILAMENT_DESCRIPTION`,
 `3DMANAGER_FILAMENT_STATE`,
 `3DMANAGER_FILAMENT_MATERIAL_LENGTH`,
 `3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH`,
 `3DMANAGER_FILAMENT_MATERIAL_THICKNESS`,
 `3DMANAGER_FILAMENT_TEMPERATURE`,
 `3DMANAGER_FILAMENT_COLOR`,
 `3DMANAGER_FILAMENT_GROUP_ID`,
 `3DMANAGER_FILAMENT_MATERIAL_TYPE`,
 `3DMANAGER_FILAMENT_WEIGHT`,
 `3DMANAGER_FILAMENT_COST`)
VALUES
('Filamento ELEGOO PLA','Bobina de color negro, compatible con la mayoría de impresoras. Comprada en amazon por rebaja',
 1,300.0000, 295.4200, 1.75, 195, '#000000', 1, 2, 1, 15.00),
('Filamento Blaco eSUN','Bobina de buena calidad, pero el material es muy útil para estructuras fuertes, no recomendable para detalles de alto nivel',
 1,325.000, 320.4200, 1.75, 205, '#ffffff', 1, 1, 1, 12.00),		
('SOLEYIN verde','Bobina especialmente útil para impresiones de alta velocidad. Compatible con mayoría de impresoras',
 1,300.000, 295.4200, 1.75, 205, '#7edd91', 1, 1, 1, 9.19);	
 		
INSERT INTO `3DMANAGER_PRINTER`
(`3DMANAGER_PRINTER_NAME`,
`3DMANAGER_PRINTER_MODEL`,
`3DMANAGER_PRINTER_STATE`,
`3DMANAGER_PRINTER_GROUP_ID`,
`3DMANAGER_PRINTER_DESCRIPTION`)
VALUES
('Impresora invitado 1','Creality Ender V1 SE',1,1,'Esta es la impresora 1 de invitado.'),
('Impresora invitado 2','Creality Ender V2 SE',2,1,'Esta es la impresora 2 de invitado.'),
('Impresora invitado 3','Creality Ender V3 SE',3,1,'Esta es la impresora 3 de invitado.')
;

INSERT INTO `3DMANAGER_3DPRINT`
(`3DMANAGER_3DPRINT_NAME`,
`3DMANAGER_3DPRINT_STATE`,
`3DMANAGER_3DPRINT_IMPRESSION_TIME`,
`3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME`,
`3DMANAGER_3DPRINT_MATERIAL_CONSUMED`,
`3DMANAGER_3DPRINT_GROUP_ID`,
`3DMANAGER_3DPRINT_PRINTER_ID`,
`3DMANAGER_3DPRINT_USER_ID`,
`3DMANAGER_3DPRINT_FILAMENT_ID`,
`3DMANAGER_3DPRINT_DESCRIPTION`)
VALUES
('Impresion 1',2,5184,4380,4.58,1,1,2,1,'Benchy test 1 con filamento 1'),
('Impresion 2',2,5184,4800,4.74,1,1,2,2,'Benchy test 2 con filamento 2'),
<<<<<<< HEAD
('Impresion 3',2,5184,5180,4.96,1,2,2,3,'Benchy test 3 con filamento 3')
=======
('Impresion 3',2,5184,5180,4.96,1,2,2,3,'Benchy test 3 con filamento 3'),
('Impresion 4 Fallida',2,5184,2000,4.2.5,1,2,2,3,'Benchy test 4 con filamento 3'),
>>>>>>> release/0.2.0
;

-- STORED PROCEDURES		
DELIMITER $$

CREATE PROCEDURE `3DMANAGER_pr_C_FILAMENT`(
    IN P_CD_GROUP INT,
    OUT CodigoError INT
)
BEGIN
    SELECT 
        `3DMANAGER_FILAMENT_ID` AS ID,
        `3DMANAGER_FILAMENT_NAME` AS DESCRIPTION
    FROM `3DMANAGER_FILAMENT`
    WHERE P_CD_GROUP = `3DMANAGER_FILAMENT`.`3DMANAGER_FILAMENT_GROUP_ID`
<<<<<<< HEAD
      AND `3DMANAGER_FILAMENT`.`3DMANAGER_FILAMENT_STATE` = 1;
=======
      AND `3DMANAGER_FILAMENT`.`3DMANAGER_FILAMENT_STATE` = 1 AND `3DMANAGER_FILAMENT_DELETED` = 0 ;
END$$

CREATE PROCEDURE `3DMANAGER_pr_C_FILAMENT_STATE`(
    OUT CodigoError INT
)
BEGIN
	SELECT 
		`3DMANAGER_C_STATE_FILAMENT_ID` AS ID,
        `3DMANAGER_C_STATE_FILAMENT_NAME` AS DESCRIPTION
    FROM `3DMANAGER_C_STATE_FILAMENT`;
>>>>>>> release/0.2.0
END$$

CREATE PROCEDURE `3DMANAGER_pr_C_FILAMENT_TYPE`()
BEGIN
<<<<<<< HEAD
    SELECT 
        `3DMANAGER_C_TYPE_FILAMENT_ID` AS ID,
        `3DMANAGER_C_TYPE_FILAMENT_NAME` AS DESCRIPTION
    FROM `3DMANAGER_C_TYPE_FILAMENT`;
END$$

CREATE PROCEDURE `3DMANAGER_pr_C_PRINT_STATE`(
    OUT CodigoError INT
)
BEGIN
    SELECT 
        `3DMANAGER_C_STATE_PRINT_ID` AS ID,
=======
	SELECT 
		`3DMANAGER_C_TYPE_FILAMENT_ID` AS ID,
        `3DMANAGER_C_TYPE_FILAMENT_NAME` AS DESCRIPTION
	FROM `3DMANAGER_C_TYPE_FILAMENT`;
END$$

CREATE  PROCEDURE `3DMANAGER_pr_C_PRINT_STATE`(
    OUT CodigoError INT
)
BEGIN
	SELECT 
		`3DMANAGER_C_STATE_PRINT_ID` AS ID,
>>>>>>> release/0.2.0
        `3DMANAGER_C_STATE_PRINT_NAME` AS DESCRIPTION
    FROM `3DMANAGER_C_STATE_PRINT`;
END$$

<<<<<<< HEAD
CREATE PROCEDURE `3DMANAGER_pr_C_PRINTER`(
    IN P_CD_GROUP INT,
    OUT CodigoError INT
)
BEGIN
    SELECT 
        `3DMANAGER_PRINTER_ID` AS ID,
        `3DMANAGER_PRINTER_NAME` AS DESCRIPTION
    FROM `3DMANAGER_PRINTER`
    WHERE P_CD_GROUP = `3DMANAGER_PRINTER`.`3DMANAGER_PRINTER_GROUP_ID`
      AND `3DMANAGER_PRINTER`.`3DMANAGER_PRINTER_STATE` = 1;
=======
CREATE  PROCEDURE `3DMANAGER_pr_C_PRINTER`(
	IN P_CD_GROUP INT,
    OUT CodigoError INT
)
BEGIN
	SELECT 
		`3DMANAGER_PRINTER_ID` AS ID,
        `3DMANAGER_PRINTER_NAME` AS DESCRIPTION
    FROM `3DMANAGER_PRINTER`
    WHERE P_CD_GROUP = `3DMANAGER_PRINTER`.`3DMANAGER_PRINTER_GROUP_ID` AND `3DMANAGER_PRINTER`.`3DMANAGER_PRINTER_STATE` = 1 AND `3DMANAGER_PRINTER_DELETED` = 0;
END$$

CREATE  PROCEDURE `3DMANAGER_pr_C_PRINTER_STATE`(
    OUT CodigoError INT
)
BEGIN
	SELECT 
		`3DMANAGER_C_STATE_PRINTER_ID` AS ID,
        `3DMANAGER_C_STATE_PRINTER_NAME` AS DESCRIPTION
    FROM `3DMANAGER_C_STATE_PRINTER`;
END$$

CREATE  PROCEDURE `3DMANAGER_pr_FILAMENT_DELETE`(
    IN P_CD_GROUP INT,
    IN P_CD_FILAMENT INT,
    OUT CodigoError INT
)
BEGIN

	DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_FILAMENT_DELETE', v_err_msg);
		COMMIT;
		
		SET CodigoError = -1;
		ROLLBACK;
	END;
    SET CodigoError = 0;
	START TRANSACTION;
		UPDATE `3DMANAGER_FILAMENT` 
        SET 
         `3DMANAGER_FILAMENT_DELETED` = 1 
        WHERE `3DMANAGER_FILAMENT_ID` = P_CD_FILAMENT AND `3DMANAGER_FILAMENT_GROUP_ID` = P_CD_GROUP;
        
        SELECT 
			`3DMANAGER_FILAMENT_ID` AS ID,
			`3DMANAGER_FILAMENT_IMAGE_KEY` AS FILE_KEY,
            `3DMANAGER_FILAMENT_IMAGE_URL` AS FILE_URL
        FROM `3DMANAGER_FILAMENT`
        WHERE `3DMANAGER_FILAMENT_ID` = P_CD_FILAMENT AND `3DMANAGER_FILAMENT_GROUP_ID` = P_CD_GROUP;
    COMMIT;
END$$

CREATE  PROCEDURE `3DMANAGER_pr_FILAMENT_DELETE_IMAGE`(
    IN P_CD_GROUP INT,
    IN P_CD_FILAMENT INT
)
BEGIN
    DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_FILAMENT_DELETE_IMAGE', v_err_msg);
		COMMIT;

		ROLLBACK;
	END;
    
	START TRANSACTION;
	UPDATE `3DMANAGER_FILAMENT` SET
        `3DMANAGER_FILAMENT_IMAGE_URL` = NULL,
        `3DMANAGER_FILAMENT_IMAGE_KEY` = NULL
    WHERE `3DMANAGER_FILAMENT_GROUP_ID` = P_CD_GROUP and  `3DMANAGER_FILAMENT_ID` = P_CD_FILAMENT ;
	COMMIT;    
		SELECT `3DMANAGER_FILAMENT_ID` FROM `3DMANAGER_FILAMENT` WHERE P_CD_FILAMENT = `3DMANAGER_FILAMENT_ID`;
END$$

CREATE PROCEDURE `3DMANAGER_pr_FILAMENT_DETAIL_GET`(
    IN P_CD_GROUP INT,
    IN P_CD_FILAMENT INT
)
BEGIN

	SELECT 
		`3DMANAGER_FILAMENT_ID` AS FILAMENT_ID,
        `3DMANAGER_FILAMENT_NAME` AS FILAMENT_NAME,
        `3DMANAGER_C_TYPE_FILAMENT_NAME` AS FILAMENT_TYPE,
        `3DMANAGER_FILAMENT_COLOR` AS FILAMENT_COLOR,
        `3DMANAGER_FILAMENT_TEMPERATURE` AS FILAMENT_TEMPERATURE,
        `3DMANAGER_FILAMENT_MATERIAL_LENGTH` AS FILAMENT_LENGHT,
        `3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH` AS FILAMENT_REMAINING_LENGHT,
        `3DMANAGER_FILAMENT_MATERIAL_THICKNESS` AS FILAMENT_THICKNESS,
        `3DMANAGER_FILAMENT_COST` AS FILAMENT_COST,
        `3DMANAGER_FILAMENT_DESCRIPTION` AS FILAMENT_DESCRIPTION,
        `3DMANAGER_FILAMENT_REGISTER_DATE`AS FILAMENT_CREATE_DATE,
        `3DMANAGER_FILAMENT_STATE` AS FILAMENT_STATE,
        (SELECT COUNT(*) 
			FROM `3DMANAGER_3DPRINT` 
			WHERE `3DMANAGER_3DPRINT_FILAMENT_ID` = P_CD_FILAMENT 
            AND `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP
			AND `3DMANAGER_3DPRINT_REGISTER_DATE` > DATE_SUB(CURDATE(), INTERVAL 1 MONTH))AS FILAMENT_PRINTED_PRINTS_MONTH,
        (SELECT COUNT(*) 
			FROM `3DMANAGER_3DPRINT` 
			WHERE `3DMANAGER_3DPRINT_FILAMENT_ID` = P_CD_FILAMENT 
            AND `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP )AS FILAMENT_PRINTED_PRINTS_TOTAL,
        `3DMANAGER_FILAMENT_IMAGE_URL` AS FILE_URL,
        `3DMANAGER_FILAMENT_IMAGE_KEY` AS FILE_KEY
        FROM `3DMANAGER_FILAMENT`
        LEFT JOIN `3DMANAGER_C_TYPE_FILAMENT` ON `3DMANAGER_C_TYPE_FILAMENT_ID` = `3DMANAGER_FILAMENT_MATERIAL_TYPE`
        WHERE `3DMANAGER_FILAMENT_ID` = P_CD_FILAMENT AND `3DMANAGER_FILAMENT_GROUP_ID` = P_CD_GROUP;
END$$

CREATE PROCEDURE `3DMANAGER_pr_FILAMENT_GET_IMAGE`(
    IN P_CD_GROUP INT,
    IN P_CD_FILAMENT INT
)
BEGIN

	SELECT 
        `3DMANAGER_FILAMENT_IMAGE_URL` AS FILE_URL,
        `3DMANAGER_FILAMENT_IMAGE_KEY` AS FILE_KEY
    FROM `3DMANAGER_FILAMENT` 
    WHERE `3DMANAGER_FILAMENT_GROUP_ID` = P_CD_GROUP and  `3DMANAGER_FILAMENT_ID` = P_CD_FILAMENT ;
>>>>>>> release/0.2.0
END$$

CREATE PROCEDURE `3DMANAGER_pr_FILAMENT_LIST`(
    IN P_CD_GROUP INT,
    OUT CodigoError INT
)
BEGIN
<<<<<<< HEAD
    SELECT 
        `3DMANAGER_FILAMENT_ID` AS FILAMENT_ID,
=======
	SELECT 
		`3DMANAGER_FILAMENT_ID` AS FILAMENT_ID,
>>>>>>> release/0.2.0
        `3DMANAGER_FILAMENT_NAME` AS FILAMENT_NAME,
        ST.`3DMANAGER_C_STATE_FILAMENT_NAME` AS FILAMENT_STATE,
        `3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH` AS FILAMENT_LENGTH,
        `3DMANAGER_FILAMENT_COST` AS FILAMENT_COST
    FROM `3DMANAGER_FILAMENT` 
<<<<<<< HEAD
    LEFT JOIN `3DMANAGER_C_STATE_FILAMENT` ST 
        ON `3DMANAGER_FILAMENT_STATE` = ST.`3DMANAGER_C_STATE_FILAMENT_ID`
    WHERE `3DMANAGER_FILAMENT_GROUP_ID` = P_CD_GROUP;
END$$

CREATE PROCEDURE `3DMANAGER_pr_FILAMENT_POST`(
    IN P_GROUP_ID INT,
=======
    LEFT JOIN `3DMANAGER_C_STATE_FILAMENT` ST ON `3DMANAGER_FILAMENT_STATE` = ST.`3DMANAGER_C_STATE_FILAMENT_ID`
    WHERE `3DMANAGER_FILAMENT_GROUP_ID` = P_CD_GROUP  AND `3DMANAGER_FILAMENT_DELETED` = 0;
END$$

CREATE PROCEDURE `3DMANAGER_pr_FILAMENT_POST`(
	IN P_GROUP_ID INT,
>>>>>>> release/0.2.0
    IN P_FILAMENT_NAME VARCHAR(100),
    IN P_FILAMENT_TYPE INT,
    IN P_FILAMENT_WEIGHT INT,
    IN P_FILAMENT_COLOR VARCHAR(10),
    IN P_FILAMENT_TEMPERATURE INT,
    IN P_FILAMENT_THICKNESS FLOAT,
    IN P_FILAMENT_COST DECIMAL(10,2),
    IN P_FILAMENT_LENGHT INT,
    IN P_FILAMENT_DESCRIPTION VARCHAR(500),
    OUT CodigoError INT
<<<<<<< HEAD
)
BEGIN
    DECLARE NEW_ID INT;

    -- If an the proc have an error SQL while running, goes to handler, do a rollback and set "CodigoError" -1
    DECLARE v_err_msg TEXT;
=======
    )
BEGIN
	
	DECLARE NEW_ID INT;
	DECLARE v_err_msg TEXT;
>>>>>>> release/0.2.0
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

<<<<<<< HEAD
		-- Independant commit
=======
		-- Forzar un commit independiente
>>>>>>> release/0.2.0
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_FILAMENT_POST', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;

    SET CodigoError = 0;
    START TRANSACTION;
<<<<<<< HEAD

    INSERT INTO `3DMANAGER_FILAMENT` (
        `3DMANAGER_FILAMENT_NAME`,
        `3DMANAGER_FILAMENT_DESCRIPTION`,
        `3DMANAGER_FILAMENT_STATE`,
        `3DMANAGER_FILAMENT_MATERIAL_LENGTH`,
        `3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH`,
        `3DMANAGER_FILAMENT_MATERIAL_THICKNESS`,
        `3DMANAGER_FILAMENT_TEMPERATURE`,
        `3DMANAGER_FILAMENT_COLOR`,
        `3DMANAGER_FILAMENT_GROUP_ID`,
        `3DMANAGER_FILAMENT_MATERIAL_TYPE`,
        `3DMANAGER_FILAMENT_WEIGHT`,
        `3DMANAGER_FILAMENT_COST`
    ) VALUES (
        P_FILAMENT_NAME,
=======
	INSERT INTO `3DMANAGER_FILAMENT` (
		`3DMANAGER_FILAMENT_NAME`,
		`3DMANAGER_FILAMENT_DESCRIPTION`,
		`3DMANAGER_FILAMENT_STATE`,
		`3DMANAGER_FILAMENT_MATERIAL_LENGTH`,
		`3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH`,
		`3DMANAGER_FILAMENT_MATERIAL_THICKNESS`,
		`3DMANAGER_FILAMENT_TEMPERATURE`,
		`3DMANAGER_FILAMENT_COLOR`,
		`3DMANAGER_FILAMENT_GROUP_ID`,
		`3DMANAGER_FILAMENT_MATERIAL_TYPE`,
		`3DMANAGER_FILAMENT_WEIGHT`,
		`3DMANAGER_FILAMENT_COST`
     
    ) VALUES (
		P_FILAMENT_NAME,
>>>>>>> release/0.2.0
        P_FILAMENT_DESCRIPTION,
        1,
        P_FILAMENT_LENGHT,
        P_FILAMENT_LENGHT,
        P_FILAMENT_THICKNESS,
        P_FILAMENT_TEMPERATURE,
        P_FILAMENT_COLOR,
        P_GROUP_ID,
        P_FILAMENT_TYPE,
        P_FILAMENT_WEIGHT,
        P_FILAMENT_COST
    );
<<<<<<< HEAD

    SET NEW_ID = LAST_INSERT_ID();
    COMMIT;

    SELECT `3DMANAGER_FILAMENT_ID` 
    FROM `3DMANAGER_FILAMENT` 
    WHERE NEW_ID = `3DMANAGER_FILAMENT_ID`;
=======
    
	SET NEW_ID = LAST_INSERT_ID();
    COMMIT;    
	SELECT NEW_ID AS `3DMANAGER_FILAMENT_ID`;
END$$

CREATE PROCEDURE `3DMANAGER_pr_FILAMENT_POST_IMAGE`(
    IN P_FILAMENT_ID INT,
    IN P_KEY VARCHAR(255),
    IN P_URL VARCHAR(255),
    OUT CodigoError INT
)
BEGIN
     -- Si hay un error SQL, se entra al handler, se hace rollback y se asigna el código -1
    DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_FILAMENT_POST_IMAGE', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;
    
    SET CodigoError = 0;
    
	START TRANSACTION;
	UPDATE `3DMANAGER_FILAMENT`
    SET `3DMANAGER_FILAMENT_IMAGE_URL` = P_URL,
		`3DMANAGER_FILAMENT_IMAGE_KEY` = P_KEY
        WHERE `3DMANAGER_FILAMENT_ID` = P_FILAMENT_ID;	
	COMMIT;    
		SELECT `3DMANAGER_FILAMENT_ID` FROM `3DMANAGER_FILAMENT` WHERE P_FILAMENT_ID = `3DMANAGER_FILAMENT_ID`;
END$$

CREATE PROCEDURE `3DMANAGER_pr_FILAMENT_UPDATE`(
    IN P_CD_GROUP INT,
    IN P_CD_FILAMENT INT,
    IN P_CD_TEMPERATURE INT,
    IN P_CD_LENGHT DECIMAL(10,4),
    IN P_DS_COLOR VARCHAR(10),
    IN P_DS_DESCRIPTION VARCHAR(500),
    IN P_DS_NAME VARCHAR(100),
    IN P_CD_COST DECIMAL(10,2),
    OUT CodigoError INT
)
BEGIN

	DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_FILAMENT_UPDATE', v_err_msg);
		COMMIT;
		
		SET CodigoError = -1;
		ROLLBACK;
	END;
    SET CodigoError = 0;
	START TRANSACTION;
		UPDATE `3DMANAGER_FILAMENT` 
        SET `3DMANAGER_FILAMENT_NAME` = P_DS_NAME ,
         `3DMANAGER_FILAMENT_DESCRIPTION` = P_DS_DESCRIPTION ,
         `3DMANAGER_FILAMENT_TEMPERATURE` = P_CD_TEMPERATURE,
		 `3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH` = P_CD_LENGHT,
         `3DMANAGER_FILAMENT_COLOR` = P_DS_COLOR,
         `3DMANAGER_FILAMENT_COST` = P_CD_COST
        WHERE `3DMANAGER_FILAMENT_ID` = P_CD_FILAMENT AND `3DMANAGER_FILAMENT_GROUP_ID` = P_CD_GROUP;
        
        SELECT ROW_COUNT() AS Total;
    COMMIT;
>>>>>>> release/0.2.0
END$$

CREATE PROCEDURE `3DMANAGER_pr_GROUP_ACCEPT_INVITATION`(
    IN P_CD_GROUP INT,
    IN P_CD_USER INT,
    IN P_IT_ACCEPTED BIT,
    OUT CodigoError INT
)
BEGIN
	
	DECLARE NEW_ID INT;
    DECLARE CONTINUE_OP BIT;
     -- Si hay un error SQL, se entra al handler, se hace rollback y se asigna el código -1
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET CodigoError = -1;
    END;
    
    SET CodigoError = 0;
	START TRANSACTION;
		
		IF( (SELECT USER_GROUP_ID FROM `3DMANAGER_USER` WHERE USER_ID = P_CD_USER) IS NULL AND
        EXISTS( SELECT 1 FROM `3DMANAGER_INVITATIONS` I WHERE I.`3DMANAGER_INVITATIONS_USER_ID` = P_CD_USER AND I.`3DMANAGER_INVITATIONS_GROUP_ID` = P_CD_GROUP) )
		THEN
			 IF (P_IT_ACCEPTED)
             THEN
				UPDATE `3DMANAGER_USER` SET USER_GROUP_ID = P_CD_GROUP,USER_ROLE = 1 WHERE USER_ID = P_CD_USER ;
				DELETE FROM `3DMANAGER_INVITATIONS` WHERE P_CD_USER = `3DMANAGER_INVITATIONS_USER_ID`;
			 ELSE
				DELETE FROM `3DMANAGER_INVITATIONS` WHERE P_CD_USER = `3DMANAGER_INVITATIONS_USER_ID` AND `3DMANAGER_INVITATIONS_GROUP_ID` = P_CD_GROUP;
			END IF;
        END IF;	
    COMMIT;    
	SELECT USER_GROUP_ID FROM `3DMANAGER_USER` WHERE USER_ID = P_CD_USER;
END$$

<<<<<<< HEAD
=======
CREATE PROCEDURE `3DMANAGER_pr_GROUP_BASIC_DATA_GET`(
IN P_CD_GROUP INT 
)
BEGIN
	SELECT 
		G.`3DMANAGER_GROUP_ID` AS GROUP_ID,
        G.`3DMANAGER_GROUP_NAME` AS GROUP_NAME,
        G.`3DMANAGER_GROUP_DESCRIPTION` AS GROUP_DESCRIPTION,
        G.`3DMANAGER_PRINTER_REGISTER_DATE` AS GROUP_DATE,
        U.`USER_NAME` AS  GROUP_OWNER
    FROM `3DMANAGER_GROUP` G
    LEFT JOIN `3DMANAGER_USER` U ON U.`USER_ID` = G.`3DMANAGER_USER_OWNER`
    WHERE `3DMANAGER_GROUP_ID` =  P_CD_GROUP;
    
    CALL `3DMANAGER_pr_USER_LIST`(P_CD_GROUP);
END$$

CREATE PROCEDURE `3DMANAGER_pr_GROUP_DASHBOARD_DATA_GET`(
IN P_CD_GROUP INT 
)
BEGIN
	SELECT 
		(SELECT SUM(`3DMANAGER_3DPRINT_IMPRESSION_TIME`)/3600 FROM `3DMANAGER_3DPRINT` 
			WHERE `3DMANAGER_3DPRINT_GROUP_ID`= P_CD_GROUP) AS GROUP_TOTAL_HOURS,
        (SELECT COUNT(*) FROM `3DMANAGER_3DPRINT` WHERE `3DMANAGER_3DPRINT_GROUP_ID`= P_CD_GROUP AND `3DMANAGER_3DPRINT_DELETED` = 0) AS GROUP_TOTAL_PRINTS,
        (SELECT SUM(`3DMANAGER_3DPRINT_MATERIAL_CONSUMED`) FROM `3DMANAGER_3DPRINT` WHERE `3DMANAGER_3DPRINT_GROUP_ID`= P_CD_GROUP) AS GROUP_TOTAL_FILAMENT,
        (SELECT COUNT(*) FROM `3DMANAGER_USER` WHERE `USER_GROUP_ID`= P_CD_GROUP) AS GROUP_TOTAL_USER,
        (SELECT COUNT(*) FROM `3DMANAGER_FILAMENT` WHERE `3DMANAGER_FILAMENT_GROUP_ID`= P_CD_GROUP AND `3DMANAGER_FILAMENT_DELETED` = 0) AS GROUP_FILAMENT_COUNT,
        (SELECT COUNT(*) FROM `3DMANAGER_PRINTER` WHERE `3DMANAGER_PRINTER_GROUP_ID`= P_CD_GROUP AND `3DMANAGER_PRINTER_DELETED` = 0) AS GROUP_TOTAL_PRINTER;
        
	SELECT 
		`3DMANAGER_PRINTER_ID` AS PRINTER_ID,
        `3DMANAGER_PRINTER_NAME` AS PRINTER_NAME,
         (SELECT SUM(`3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME`)/3600 FROM `3DMANAGER_3DPRINT`
			WHERE `3DMANAGER_3DPRINT_PRINTER_ID` = P.`3DMANAGER_PRINTER_ID`) AS PRINTER_HOURS
    FROM `3DMANAGER_PRINTER` P
    LEFT JOIN `3DMANAGER_3DPRINT` PR ON PR.`3DMANAGER_3DPRINT_PRINTER_ID` = P.`3DMANAGER_PRINTER_ID`
    WHERE `3DMANAGER_PRINTER_GROUP_ID` = P_CD_GROUP AND `3DMANAGER_PRINTER_DELETED` = 0 GROUP BY PRINTER_ID  ; 
END$$

CREATE PROCEDURE `3DMANAGER_pr_GROUP_DELETE`(
    IN P_CD_GROUP INT,
    IN P_CD_USER INT,
    OUT CodigoError INT
)
BEGIN

	DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_GROUP_DELETE', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;
    SET CodigoError = 0;
	START TRANSACTION;
    
		IF (SELECT `3DMANAGER_USER_OWNER` FROM `3DMANAGER_GROUP` WHERE `3DMANAGER_GROUP_ID` = P_CD_GROUP) = P_CD_USER THEN
			UPDATE `3DMANAGER_USER` 
				SET `USER_ROLE` = NULL ,
                `USER_GROUP_ID` = null
                WHERE USER_GROUP_ID = P_CD_GROUP;
            
            
            DELETE FROM `3DMANAGER_3DPRINT` WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP;
            DELETE FROM `3DMANAGER_PRINTER` WHERE `3DMANAGER_PRINTER_GROUP_ID` = P_CD_GROUP;
            DELETE FROM `3DMANAGER_FILAMENT` WHERE `3DMANAGER_FILAMENT_GROUP_ID` = P_CD_GROUP;
            DELETE FROM `3DMANAGER_GROUP` WHERE `3DMANAGER_GROUP_ID` = P_CD_GROUP;
            
		END IF;
    COMMIT;
END$$

>>>>>>> release/0.2.0
CREATE PROCEDURE `3DMANAGER_pr_GROUP_INVITATIONS`(
	IN P_CD_USER INT
)
BEGIN
	SELECT 
		U.USER_NAME AS 'USER_OWNER',
        G.`3DMANAGER_GROUP_ID` as 'GROUP_ID',
        G.`3DMANAGER_GROUP_NAME` as 'GROUP_NAME',
        G.`3DMANAGER_GROUP_DESCRIPTION` as 'GROUP_DESCRIPTION'
    FROM `3DMANAGER_INVITATIONS` I
    LEFT JOIN `3DMANAGER_GROUP` G ON G.`3DMANAGER_GROUP_ID` = I.`3DMANAGER_INVITATIONS_GROUP_ID`
    LEFT JOIN `3DMANAGER_USER` U ON U.USER_ID = G.`3DMANAGER_USER_OWNER`
    WHERE P_CD_USER = I.`3DMANAGER_INVITATIONS_USER_ID`;
END$$

<<<<<<< HEAD
=======
CREATE PROCEDURE `3DMANAGER_pr_GROUP_KICK_USER`(
    IN P_CD_USER_KICKED INT,
    OUT CodigoError INT
)
BEGIN

	DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_GROUP_KICK_USER', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;
    SET CodigoError = 0;
	START TRANSACTION;
		
        UPDATE `3DMANAGER_USER` 
			SET USER_GROUP_ID = null,
			USER_ROLE = NULL
			WHERE USER_ID = P_CD_USER_KICKED;
        
        IF ROW_COUNT() = 0 THEN 
			SET CodigoError = -1;
            ROLLBACK; 
		END IF;
    
    COMMIT;
END$$

CREATE PROCEDURE `3DMANAGER_pr_GROUP_LEAVE`(
    IN P_CD_USER INT,
    OUT CodigoError INT
)
BEGIN

	DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_GROUP_LEAVE', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;
    SET CodigoError = 0;
	START TRANSACTION;
		
        UPDATE `3DMANAGER_USER` 
			SET USER_GROUP_ID = null,
            USER_ROLE = NULL
			WHERE USER_ID = P_CD_USER;
        
        IF ROW_COUNT() = 0 THEN 
			SET CodigoError = -1;
            ROLLBACK; 
		END IF;
    
    COMMIT;
END$$

>>>>>>> release/0.2.0
CREATE PROCEDURE `3DMANAGER_pr_GROUP_POST`(
    IN P_CD_USER_ID INT,
    IN P_DS_GROUP_NAME VARCHAR(100),
    IN P_DS_GROUP_DESCRIPTION VARCHAR(500),
    OUT CodigoError INT
)
BEGIN

<<<<<<< HEAD
	-- If an the proc have an error SQL while running, goes to handler, do a rollback and set "CodigoError" -1
    DECLARE v_err_msg TEXT;
=======
	DECLARE v_err_msg TEXT;
>>>>>>> release/0.2.0
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

<<<<<<< HEAD
		-- Independant commit
=======
		-- Forzar un commit independiente
>>>>>>> release/0.2.0
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_GROUP_POST', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;
    SET CodigoError = 0;
	START TRANSACTION;
    IF EXISTS (
        SELECT 1 FROM `3DMANAGER_GROUP` WHERE `3DMANAGER_GROUP_NAME` = P_DS_GROUP_NAME
    ) THEN
        SET CodigoError = 4091;
    ELSE
<<<<<<< HEAD
        INSERT INTO 3DMANAGER_GROUP (`3DMANAGER_GROUP_NAME`,`3DMANAGER_GROUP_DESCRIPTION`,`3DMANAGER_USER_OWNER`)
=======
        INSERT INTO `3DMANAGER_GROUP` (`3DMANAGER_GROUP_NAME`,`3DMANAGER_GROUP_DESCRIPTION`,`3DMANAGER_USER_OWNER`)
>>>>>>> release/0.2.0
        VALUES (P_DS_GROUP_NAME, P_DS_GROUP_DESCRIPTION ,P_CD_USER_ID);
        
        UPDATE `3DMANAGER_USER` 
			SET USER_ROLE = 2,
				USER_GROUP_ID = (SELECT `3DMANAGER_GROUP_ID` FROM `3DMANAGER_GROUP` WHERE P_DS_GROUP_NAME = `3DMANAGER_GROUP_NAME`)
			WHERE USER_ID = P_CD_USER_ID;
        
        SELECT `3DMANAGER_GROUP_NAME` FROM `3DMANAGER_GROUP` WHERE P_DS_GROUP_NAME = `3DMANAGER_GROUP_NAME`;
    END IF;
    
    COMMIT;
END$$

<<<<<<< HEAD
CREATE PROCEDURE `3DMANAGER_pr_PRINT_LIST`(
=======
CREATE PROCEDURE `3DMANAGER_pr_GROUP_TRANSFER_OWNERSHIP`(
    IN P_CD_USER INT,
    IN P_CD_NEW_OWNER INT,
>>>>>>> release/0.2.0
    IN P_CD_GROUP INT,
    OUT CodigoError INT
)
BEGIN
<<<<<<< HEAD
=======

	DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_GROUP_TRANSFER_OWNERSHIP', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;
    SET CodigoError = 0;
	START TRANSACTION;
		
        UPDATE `3DMANAGER_USER` 
			SET USER_ROLE = 1
			WHERE USER_ID = P_CD_USER AND USER_GROUP_ID = P_CD_GROUP ;
        
        UPDATE `3DMANAGER_USER` 
			SET USER_ROLE = 2
			WHERE USER_ID = P_CD_NEW_OWNER AND USER_GROUP_ID = P_CD_GROUP;
        
        UPDATE `3DMANAGER_GROUP`
			SET `3DMANAGER_USER_OWNER` = P_CD_NEW_OWNER
			WHERE `3DMANAGER_GROUP_ID` = P_CD_GROUP;
            
        IF ROW_COUNT() = 0 THEN 
			SET CodigoError = -1;
            ROLLBACK; 
		END IF;
    
    COMMIT;
END$$

CREATE PROCEDURE `3DMANAGER_pr_GROUP_UPDATE`(
    IN P_CD_USER_ID INT,
    IN P_DS_GROUP_NAME VARCHAR(100),
    IN P_DS_GROUP_DESCRIPTION VARCHAR(500),
    IN P_CD_GROUP INT,
    OUT CodigoError INT
)
BEGIN

	DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_GROUP_UPDATE', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;
    SET CodigoError = 0;
	START TRANSACTION;
		UPDATE  `3DMANAGER_GROUP` 
        SET `3DMANAGER_GROUP_NAME` = P_DS_GROUP_NAME,`3DMANAGER_GROUP_DESCRIPTION` = P_DS_GROUP_DESCRIPTION
		WHERE `3DMANAGER_USER_OWNER` = P_CD_USER_ID AND `3DMANAGER_GROUP_ID` = P_CD_GROUP;
		
		SELECT `3DMANAGER_GROUP_NAME` FROM `3DMANAGER_GROUP` WHERE P_DS_GROUP_NAME = `3DMANAGER_GROUP_NAME`;
    COMMIT;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINT_COMMENT_POST`(
    IN P_COMMENT VARCHAR(500),
    IN P_USER_ID INT,
    IN P_PRINT_ID INT,
    OUT CodigoError INT
)
BEGIN
	DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_PRINT_COMMENT_POST', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;

    SET CodigoError = 0;
    START TRANSACTION;
		INSERT INTO `3DMANAGER_COMMENT`
		(
			`3DMANAGER_COMMENT_COMMENT`,
			`3DMANAGER_COMMENT_USER_ID`,
			`3DMANAGER_COMMENT_3DPRINT_ID`
		)
		VALUES 
		(
			P_COMMENT,
			P_USER_ID,
			P_PRINT_ID
		);
		COMMIT;
    SELECT LAST_INSERT_ID() AS COMMENT_ID;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINT_COMMENTS_LIST`(
    IN P_CD_GROUP INT,
    IN P_PRINT_ID INT
)
BEGIN
    SELECT 
        C.`3DMANAGER_COMMENT_ID` AS ID_COMMENT,
        C.`3DMANAGER_COMMENT_COMMENT` AS DS_COMMENT,
        C.`3DMANAGER_COMMENT_USER_ID` AS COMMENT_USER_ID,
        U.`USER_NAME` AS COMMENT_USER_NAME,
        C.`3DMANAGER_COMMENT_REGISTER_DATE` AS COMMENT_DATE
    FROM `3DMANAGER_COMMENT` C
    LEFT JOIN `3DMANAGER_USER` U
        ON U.USER_ID = C.`3DMANAGER_COMMENT_USER_ID`
	LEFT JOIN `3DMANAGER_3DPRINT` P ON P.`3DMANAGER_3DPRINT_ID` = C.`3DMANAGER_COMMENT_3DPRINT_ID` 
    WHERE C.`3DMANAGER_COMMENT_3DPRINT_ID` = P_PRINT_ID
      AND P.`3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP
    ORDER BY C.`3DMANAGER_COMMENT_REGISTER_DATE` ASC;

END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINT_DELETE`(
    IN P_CD_GROUP INT,
    IN P_CD_PRINT INT,
    OUT CodigoError INT
)
BEGIN

	DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_PRINT_DELETE', v_err_msg);
		COMMIT;
		
		SET CodigoError = -1;
		ROLLBACK;
	END;
    SET CodigoError = 0;
	START TRANSACTION;
		UPDATE `3DMANAGER_3DPRINT` 
        SET 
         `3DMANAGER_3DPRINT_DELETED` = 1 
        WHERE `3DMANAGER_3DPRINT_ID` = P_CD_PRINT AND `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP;
        
        SELECT 
			`3DMANAGER_3DPRINT_ID` AS ID,
			`3DMANAGER_3DPRINT_IMAGE_KEY` AS FILE_KEY,
            `3DMANAGER_3DPRINT_IMAGE_URL` AS FILE_URL
        FROM `3DMANAGER_3DPRINT` 
        WHERE `3DMANAGER_3DPRINT_ID` = P_CD_PRINT AND `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP;
    COMMIT;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINT_DETAIL_GET`(
    IN P_CD_GROUP INT,
    IN P_CD_PRINT INT
)
BEGIN

	SELECT 
		P.`3DMANAGER_3DPRINT_ID` AS PRINT_ID,
        P.`3DMANAGER_3DPRINT_FILAMENT_ID` AS PRINT_FILAMENT_ID,
        F.`3DMANAGER_FILAMENT_NAME` AS PRINT_FILAMENT_NAME,
        TP.`3DMANAGER_C_TYPE_FILAMENT_NAME` AS PRINT_MATERIAL,
        P.`3DMANAGER_3DPRINT_PRINTER_ID` AS PRINT_PRINTER_ID,
        PR.`3DMANAGER_PRINTER_NAME` AS PRINT_PRINTER_NAME,
        P.`3DMANAGER_3DPRINT_USER_ID` AS PRINT_USER_ID,
        U.`USER_NAME` AS PRINT_USER_NAME,
        P.`3DMANAGER_3DPRINT_NAME` AS PRINT_NAME,
        S.`3DMANAGER_C_STATE_PRINT_ID` AS PRINT_STATE,
        P.`3DMANAGER_3DPRINT_DESCRIPTION` AS PRINT_DESCRIPTION,
        P.`3DMANAGER_3DPRINT_REGISTER_DATE` AS PRINT_DATE_CREATE_TIME,
        P.`3DMANAGER_3DPRINT_MATERIAL_CONSUMED` AS PRINT_MATERIAL_CONSUMED,
        P.`3DMANAGER_3DPRINT_IMPRESSION_TIME` AS PRINT_TIME_IMPRESSION,
        P.`3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME` AS PRINT_REAL_TIME_IMPRESSION,
        F.`3DMANAGER_FILAMENT_COST_PER_METER` AS FILAMENT_COST,
        P.`3DMANAGER_3DPRINT_IMAGE_URL` AS FILE_URL,
        P.`3DMANAGER_3DPRINT_IMAGE_KEY` AS FILE_KEY
    FROM `3DMANAGER_3DPRINT` P
    LEFT JOIN `3DMANAGER_FILAMENT` F ON F.`3DMANAGER_FILAMENT_ID` = P.`3DMANAGER_3DPRINT_FILAMENT_ID`
    LEFT JOIN `3DMANAGER_USER` U ON U.`USER_ID` = P.`3DMANAGER_3DPRINT_USER_ID`
    LEFT JOIN `3DMANAGER_PRINTER` PR ON PR.`3DMANAGER_PRINTER_ID` = P.`3DMANAGER_3DPRINT_PRINTER_ID`
    LEFT JOIN `3DMANAGER_C_STATE_PRINT` S ON S.`3DMANAGER_C_STATE_PRINT_ID` = P.`3DMANAGER_3DPRINT_STATE`
    LEFT JOIN `3DMANAGER_C_TYPE_FILAMENT` TP ON F.`3DMANAGER_FILAMENT_MATERIAL_TYPE` = TP.`3DMANAGER_C_TYPE_FILAMENT_ID`
    WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP and  `3DMANAGER_3DPRINT_ID` = P_CD_PRINT ;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINT_LIST`(
    IN P_CD_GROUP INT,
    IN P_PAGE_NUMBER INT,
    IN P_PAGE_SIZE INT,
    OUT CodigoError INT
)
BEGIN
	DECLARE PAGE_OFFSET INT;
    SET PAGE_OFFSET = (P_PAGE_NUMBER - 1) * P_PAGE_SIZE;
    
>>>>>>> release/0.2.0
	SELECT 
		`3DMANAGER_3DPRINT_ID` AS PRINT_ID,
        `3DMANAGER_3DPRINT_NAME` AS PRINT_NAME,
        `USER_NAME` AS PRINT_USER,
        `3DMANAGER_3DPRINT_REGISTER_DATE` AS PRINT_DATE,
<<<<<<< HEAD
        `3DMANAGER_3DPRINT_IMPRESSION_TIME` AS PRINT_TIME,
        `3DMANAGER_3DPRINT_MATERIAL_CONSUMED` AS PRINT_FILAMENT_USED
    FROM `3DMANAGER_3DPRINT` 
    LEFT JOIN `3DMANAGER_USER` ON `3DMANAGER_3DPRINT_USER_ID` = `USER_ID`
    WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP  ;
=======
        `3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME` AS PRINT_TIME,
        `3DMANAGER_3DPRINT_MATERIAL_CONSUMED` AS PRINT_FILAMENT_USED
    FROM `3DMANAGER_3DPRINT` 
    LEFT JOIN `3DMANAGER_USER` ON `3DMANAGER_3DPRINT_USER_ID` = `USER_ID`
    WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP AND `3DMANAGER_3DPRINT_DELETED` = 0
    ORDER BY `3DMANAGER_3DPRINT_REGISTER_DATE` DESC LIMIT P_PAGE_SIZE OFFSET PAGE_OFFSET;
    
    SELECT COUNT(*) AS TOTAL_ITEMS 
    FROM `3DMANAGER_3DPRINT` 
    WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP AND `3DMANAGER_3DPRINT_DELETED` = 0; 
    
    SET CodigoError = 0;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINT_LIST_OF_FILAMENT`(
    IN P_CD_GROUP INT,
    IN P_PAGE_NUMBER INT,
    IN P_PAGE_SIZE INT,
    IN P_ID INT
)
BEGIN
	DECLARE PAGE_OFFSET INT;
    SET PAGE_OFFSET = (P_PAGE_NUMBER - 1) * P_PAGE_SIZE;
    
	SELECT 
		`3DMANAGER_3DPRINT_ID` AS PRINT_ID,
        `3DMANAGER_3DPRINT_NAME` AS PRINT_NAME,
        `USER_NAME` AS PRINT_USER,
        `3DMANAGER_3DPRINT_REGISTER_DATE` AS PRINT_DATE,
        `3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME` AS PRINT_TIME,
        `3DMANAGER_3DPRINT_MATERIAL_CONSUMED` AS PRINT_FILAMENT_USED
    FROM `3DMANAGER_3DPRINT` 
    LEFT JOIN `3DMANAGER_USER` ON `3DMANAGER_3DPRINT_USER_ID` = `USER_ID`
    WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP  AND `3DMANAGER_3DPRINT_FILAMENT_ID` = P_ID AND `3DMANAGER_3DPRINT_DELETED` = 0
    ORDER BY `3DMANAGER_3DPRINT_REGISTER_DATE` DESC LIMIT P_PAGE_SIZE OFFSET PAGE_OFFSET;
    
    SELECT COUNT(*) AS TOTAL_ITEMS 
    FROM `3DMANAGER_3DPRINT` 
    WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP AND  `3DMANAGER_3DPRINT_FILAMENT_ID` = P_ID AND `3DMANAGER_3DPRINT_DELETED` = 0; 
    
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINT_LIST_OF_PRINTER`(
    IN P_CD_GROUP INT,
    IN P_PAGE_NUMBER INT,
    IN P_PAGE_SIZE INT,
    IN P_ID INT
)
BEGIN
	DECLARE PAGE_OFFSET INT;
    SET PAGE_OFFSET = (P_PAGE_NUMBER - 1) * P_PAGE_SIZE;
    
	SELECT 
		`3DMANAGER_3DPRINT_ID` AS PRINT_ID,
        `3DMANAGER_3DPRINT_NAME` AS PRINT_NAME,
        `USER_NAME` AS PRINT_USER,
        `3DMANAGER_3DPRINT_REGISTER_DATE` AS PRINT_DATE,
        `3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME` AS PRINT_TIME,
        `3DMANAGER_3DPRINT_MATERIAL_CONSUMED` AS PRINT_FILAMENT_USED
    FROM `3DMANAGER_3DPRINT` 
    LEFT JOIN `3DMANAGER_USER` ON `3DMANAGER_3DPRINT_USER_ID` = `USER_ID`
    WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP  AND `3DMANAGER_3DPRINT_PRINTER_ID` = P_ID AND `3DMANAGER_3DPRINT_DELETED` = 0
    ORDER BY `3DMANAGER_3DPRINT_REGISTER_DATE` DESC LIMIT P_PAGE_SIZE OFFSET PAGE_OFFSET;
    
    SELECT COUNT(*) AS TOTAL_ITEMS 
    FROM `3DMANAGER_3DPRINT` 
    WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP AND `3DMANAGER_3DPRINT_PRINTER_ID` = P_ID AND `3DMANAGER_3DPRINT_DELETED` = 0; 
    
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINT_LIST_OF_USER`(
    IN P_CD_GROUP INT,
    IN P_PAGE_NUMBER INT,
    IN P_PAGE_SIZE INT,
    IN P_ID INT
)
BEGIN
	DECLARE PAGE_OFFSET INT;
    SET PAGE_OFFSET = (P_PAGE_NUMBER - 1) * P_PAGE_SIZE;
    
	SELECT 
		`3DMANAGER_3DPRINT_ID` AS PRINT_ID,
        `3DMANAGER_3DPRINT_NAME` AS PRINT_NAME,
        `USER_NAME` AS PRINT_USER,
        `3DMANAGER_3DPRINT_REGISTER_DATE` AS PRINT_DATE,
        `3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME` AS PRINT_TIME,
        `3DMANAGER_3DPRINT_MATERIAL_CONSUMED` AS PRINT_FILAMENT_USED
    FROM `3DMANAGER_3DPRINT` 
    LEFT JOIN `3DMANAGER_USER` ON `3DMANAGER_3DPRINT_USER_ID` = `USER_ID`
    WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP  AND `3DMANAGER_3DPRINT_USER_ID` = P_ID AND `3DMANAGER_3DPRINT_DELETED` = 0
    ORDER BY `3DMANAGER_3DPRINT_REGISTER_DATE` DESC LIMIT P_PAGE_SIZE OFFSET PAGE_OFFSET;
    
    SELECT COUNT(*) AS TOTAL_ITEMS 
    FROM `3DMANAGER_3DPRINT` 
    WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP AND `3DMANAGER_3DPRINT_USER_ID` = P_ID AND `3DMANAGER_3DPRINT_DELETED` = 0; 
    
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINT_LIST_TIMES`(
    IN P_CD_GROUP INT,
    IN P_CD_PRINTER INT
)
BEGIN
	SELECT 
        `3DMANAGER_3DPRINT_IMPRESSION_TIME` AS PRINTER_TIME,
        `3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME` AS PRINTER_TIME_REAL
    FROM `3DMANAGER_3DPRINT` 
    LEFT JOIN `3DMANAGER_USER` ON `3DMANAGER_3DPRINT_USER_ID` = `USER_ID`
    WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP  AND `3DMANAGER_3DPRINT_PRINTER_ID` = P_CD_PRINTER 
    AND `3DMANAGER_3DPRINT_STATE` = 1 AND `3DMANAGER_3DPRINT_DELETED` = 0; 
>>>>>>> release/0.2.0
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINT_POST`(
    IN P_GROUP_ID INT,
    IN P_USER_ID INT,
    IN P_PRINT_NAME VARCHAR(100),
    IN P_PRINT_STATE INT,
    IN P_PRINT_PRINTER_ID INT,
    IN P_PRINT_FILAMENT_ID INT,
    IN P_PRINT_DESCRIPTION VARCHAR(500),
    IN P_PRINT_TIME INT,
    IN P_PRINT_FILAMENT_USED DECIMAL(10,2),
    IN P_PRINT_REAL_TIME INT,
<<<<<<< HEAD
=======
    IN P_PRINT_PROGRESS INT,
>>>>>>> release/0.2.0
    OUT CodigoError INT
)
BEGIN
    DECLARE NEW_ID INT;
    DECLARE CURRENT_FILAMENT_LENGTH DECIMAL(10,2);
    DECLARE v_err_msg TEXT;
    DECLARE NEW_STATE INT;
<<<<<<< HEAD
=======
    DECLARE REAL_FILAMENT_USED DECIMAL(10,2);

>>>>>>> release/0.2.0
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

<<<<<<< HEAD
		-- Independant commit
=======
		-- Forzar un commit independiente
>>>>>>> release/0.2.0
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_PRINT_POST', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;
    
    SET CodigoError = 0;
    START TRANSACTION;
<<<<<<< HEAD
=======
	
    SET REAL_FILAMENT_USED = 
        CASE 
            WHEN P_PRINT_STATE = 3 THEN (P_PRINT_FILAMENT_USED * (P_PRINT_PROGRESS / 100))
            ELSE P_PRINT_FILAMENT_USED
        END;
>>>>>>> release/0.2.0

    SELECT `3DMANAGER_FILAMENT`.`3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH`
    INTO CURRENT_FILAMENT_LENGTH
    FROM `3DMANAGER_FILAMENT`
    WHERE `3DMANAGER_FILAMENT`.`3DMANAGER_FILAMENT_ID` = P_PRINT_FILAMENT_ID;

<<<<<<< HEAD
    SET CURRENT_FILAMENT_LENGTH = CURRENT_FILAMENT_LENGTH - P_PRINT_FILAMENT_USED;
=======
    SET CURRENT_FILAMENT_LENGTH = CURRENT_FILAMENT_LENGTH - REAL_FILAMENT_USED;
>>>>>>> release/0.2.0
	SET  NEW_STATE = CASE WHEN CURRENT_FILAMENT_LENGTH <= 0 THEN 2 ELSE 1 END;
    
    INSERT INTO `3DMANAGER_3DPRINT` (
        `3DMANAGER_3DPRINT_NAME`,
        `3DMANAGER_3DPRINT_DESCRIPTION`,
        `3DMANAGER_3DPRINT_STATE`,
        `3DMANAGER_3DPRINT_IMPRESSION_TIME`,
        `3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME`,
        `3DMANAGER_3DPRINT_GROUP_ID`,
        `3DMANAGER_3DPRINT_FILAMENT_ID`,
        `3DMANAGER_3DPRINT_USER_ID`,
        `3DMANAGER_3DPRINT_PRINTER_ID`,
        `3DMANAGER_3DPRINT_MATERIAL_CONSUMED` 
    ) VALUES (
        P_PRINT_NAME,
        P_PRINT_DESCRIPTION,
        P_PRINT_STATE,
        P_PRINT_TIME,
        P_PRINT_REAL_TIME,
        P_GROUP_ID,
        P_PRINT_FILAMENT_ID,
        P_USER_ID,
        P_PRINT_PRINTER_ID,
<<<<<<< HEAD
        P_PRINT_FILAMENT_USED
=======
        REAL_FILAMENT_USED
>>>>>>> release/0.2.0
    );

    SET NEW_ID = LAST_INSERT_ID();

    UPDATE `3DMANAGER_FILAMENT` 
    SET `3DMANAGER_FILAMENT`.`3DMANAGER_FILAMENT_MATERIAL_REMAINING_LENGTH` = CURRENT_FILAMENT_LENGTH,
		`3DMANAGER_FILAMENT`.`3DMANAGER_FILAMENT_STATE` = NEW_STATE
    WHERE `3DMANAGER_FILAMENT_ID` = P_PRINT_FILAMENT_ID;
	
    COMMIT;

<<<<<<< HEAD
    SELECT NEW_ID AS PRINT_ID;
=======
    SELECT NEW_ID AS `3DMANAGER_3DPRINT_ID`;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINT_POST_IMAGE`(
    IN P_PRINT_ID INT,
    IN P_KEY VARCHAR(255),
    IN P_URL VARCHAR(255),
    OUT CodigoError INT
)
BEGIN
     -- Si hay un error SQL, se entra al handler, se hace rollback y se asigna el código -1
    DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_PRINT_POST_IMAGE', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;
    SET CodigoError = 0;
    
	START TRANSACTION;
	UPDATE `3DMANAGER_3DPRINT`
    SET `3DMANAGER_3DPRINT_IMAGE_URL` = P_URL,
		`3DMANAGER_3DPRINT_IMAGE_KEY` = P_KEY
        WHERE `3DMANAGER_3DPRINT_ID` = P_PRINT_ID;	
	COMMIT;    
		SELECT `3DMANAGER_3DPRINT_ID` FROM `3DMANAGER_3DPRINT` WHERE P_PRINT_ID = `3DMANAGER_3DPRINT_ID`;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINT_UPDATE`(
    IN P_CD_GROUP INT,
    IN P_CD_PRINT INT,
    IN P_DS_NAME VARCHAR(100),
    IN P_DS_DESCRIPTION VARCHAR(500),
    OUT CodigoError INT
)
BEGIN

	DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_PRINT_UPDATE', v_err_msg);
		COMMIT;
		
		SET CodigoError = -1;
		ROLLBACK;
	END;
    SET CodigoError = 0;
	START TRANSACTION;
		UPDATE `3DMANAGER_3DPRINT` 
        SET 
         `3DMANAGER_3DPRINT_NAME` = P_DS_NAME ,
         `3DMANAGER_3DPRINT_DESCRIPTION` = P_DS_DESCRIPTION 
        WHERE `3DMANAGER_3DPRINT_ID` = P_CD_PRINT AND `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP;
        
        SELECT ROW_COUNT() AS Total;
    COMMIT;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINTER_DELETE`(
    IN P_CD_GROUP INT,
    IN P_CD_PRINTER INT,
    OUT CodigoError INT
)
BEGIN

	DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_PRINTER_DELETE', v_err_msg);
		COMMIT;
		
		SET CodigoError = -1;
		ROLLBACK;
	END;
    SET CodigoError = 0;
	START TRANSACTION;
		UPDATE `3DMANAGER_PRINTER` 
        SET 
         `3DMANAGER_PRINTER_DELETED` = 1 
        WHERE `3DMANAGER_PRINTER_ID` = P_CD_PRINTER AND `3DMANAGER_PRINTER_GROUP_ID` = P_CD_GROUP;
        
        SELECT 
			`3DMANAGER_PRINTER_ID` AS ID,
			`3DMANAGER_PRINTER_IMAGE_KEY` AS FILE_KEY,
            `3DMANAGER_PRINTER_IMAGE_URL` AS FILE_URL
        FROM `3DMANAGER_PRINTER`
        WHERE `3DMANAGER_PRINTER_ID` = P_CD_PRINTER AND `3DMANAGER_PRINTER_GROUP_ID` = P_CD_GROUP;
    COMMIT;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINTER_DELETE_IMAGE`(
    IN P_CD_GROUP INT,
    IN P_CD_PRINTER INT
)
BEGIN
    DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_PRINTER_DELETE_IMAGE', v_err_msg);
		COMMIT;

		ROLLBACK;
	END;
    
	START TRANSACTION;
	UPDATE `3DMANAGER_PRINTER` SET
        `3DMANAGER_PRINTER_IMAGE_URL` = NULL,
        `3DMANAGER_PRINTER_IMAGE_KEY` = NULL
    WHERE `3DMANAGER_PRINTER_GROUP_ID` = P_CD_GROUP and  `3DMANAGER_PRINTER_ID` = P_CD_PRINTER ;
	COMMIT;    
		SELECT `3DMANAGER_PRINTER_ID` FROM `3DMANAGER_PRINTER` WHERE P_CD_PRINTER = `3DMANAGER_PRINTER_ID`;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINTER_DETAIL_GET`(
    IN P_CD_GROUP INT,
    IN P_CD_PRINTER INT
)
BEGIN

	SELECT 
		`3DMANAGER_PRINTER_ID` AS PRINTER_ID,
        `3DMANAGER_PRINTER_NAME` AS PRINTER_NAME,
        `3DMANAGER_PRINTER_MODEL` AS PRINTER_MODEL,
        `3DMANAGER_PRINTER_DESCRIPTION` AS PRINTER_DESCRIPTION,
        `3DMANAGER_PRINTER_STATE` AS PRINTER_STATE_ID,
        `3DMANAGER_C_STATE_PRINTER_NAME` AS PRINTER_STATE_NAME,
        `3DMANAGER_PRINTER_REGISTER_DATE` AS PRINTER_CREATE_DATE,
        (SELECT SUM(`3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME`)/3600
			FROM `3DMANAGER_3DPRINT`
            WHERE `3DMANAGER_3DPRINT_PRINTER_ID` = P_CD_PRINTER
				AND `3DMANAGER_3DPRINT_GROUP_ID`= P_CD_GROUP) AS PRINTER_TOTAL_HOURS,
        (SELECT SUM(`3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME`)/3600 
			FROM `3DMANAGER_3DPRINT`
			WHERE `3DMANAGER_3DPRINT_PRINTER_ID` = P_CD_PRINTER 
				AND `3DMANAGER_3DPRINT_GROUP_ID`= P_CD_GROUP 
                AND `3DMANAGER_3DPRINT_REGISTER_DATE` > DATE_SUB(CURDATE(), INTERVAL 1 MONTH)) AS PRINTER_TOTAL_HOURS_MONTH,
        (SELECT COUNT(*) FROM `3DMANAGER_3DPRINT` 
			WHERE `3DMANAGER_3DPRINT_PRINTER_ID` = P_CD_PRINTER 
            AND `3DMANAGER_3DPRINT_GROUP_ID`= P_CD_GROUP 
             ) AS PRINTER_TOTAL_PRINTS,
        (SELECT COUNT(*) FROM `3DMANAGER_3DPRINT` 
			WHERE `3DMANAGER_3DPRINT_PRINTER_ID` = P_CD_PRINTER 
            AND `3DMANAGER_3DPRINT_GROUP_ID`= P_CD_GROUP
            AND `3DMANAGER_3DPRINT_REGISTER_DATE` > DATE_SUB(CURDATE(), INTERVAL 1 MONTH)) AS PRINTER_TOTAL_PRINTS_MONTH,
        `3DMANAGER_PRINTER_IMAGE_URL` AS FILE_URL,
        `3DMANAGER_PRINTER_IMAGE_KEY` AS FILE_KEY,
         (SELECT COUNT(*) FROM `3DMANAGER_3DPRINT` 
			WHERE `3DMANAGER_3DPRINT_PRINTER_ID` = P_CD_PRINTER 
            AND `3DMANAGER_3DPRINT_GROUP_ID`= P_CD_GROUP 
            AND `3DMANAGER_3DPRINT_STATE`= 1 ) AS PRINTER_COMPLETE_PRINTS, 
		(SELECT COUNT(*) FROM `3DMANAGER_3DPRINT` 
			WHERE `3DMANAGER_3DPRINT_PRINTER_ID` = P_CD_PRINTER 
            AND `3DMANAGER_3DPRINT_GROUP_ID`= P_CD_GROUP 
            AND `3DMANAGER_3DPRINT_STATE`= 2 ) AS PRINTER_NO_COMPLETE_PRINTS,
		(SELECT COUNT(*) FROM `3DMANAGER_3DPRINT` 
			WHERE `3DMANAGER_3DPRINT_PRINTER_ID` = P_CD_PRINTER 
            AND `3DMANAGER_3DPRINT_GROUP_ID`= P_CD_GROUP
            AND `3DMANAGER_3DPRINT_STATE`= 1
            AND `3DMANAGER_3DPRINT_REGISTER_DATE` > DATE_SUB(CURDATE(), INTERVAL 1 MONTH)) AS PRINTER_COMPLETE_PRINTS_MONTH
    FROM `3DMANAGER_PRINTER` 
    LEFT JOIN `3DMANAGER_C_STATE_PRINTER` ON `3DMANAGER_C_STATE_PRINTER_ID` = `3DMANAGER_PRINTER_STATE`
    WHERE `3DMANAGER_PRINTER_GROUP_ID` = P_CD_GROUP and  `3DMANAGER_PRINTER_ID` = P_CD_PRINTER ;
END$$

CREATE  PROCEDURE `3DMANAGER_pr_PRINTER_GET_IMAGE`(
    IN P_CD_GROUP INT,
    IN P_CD_PRINTER INT
)
BEGIN
	SELECT 
        `3DMANAGER_PRINTER_IMAGE_URL` AS FILE_URL,
        `3DMANAGER_PRINTER_IMAGE_KEY` AS FILE_KEY
    FROM `3DMANAGER_PRINTER` 
    WHERE `3DMANAGER_PRINTER_GROUP_ID` = P_CD_GROUP and  `3DMANAGER_PRINTER_ID` = P_CD_PRINTER ;
>>>>>>> release/0.2.0
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINTER_LIST`(
    IN P_CD_GROUP INT,
    OUT CodigoError INT
)
BEGIN
	SELECT 
		`3DMANAGER_PRINTER_ID` AS PRINTER_ID,
        `3DMANAGER_PRINTER_NAME` AS PRINTER_NAME,
        `3DMANAGER_PRINTER_MODEL` AS PRINTER_MODEL,
        `3DMANAGER_PRINTER_DESCRIPTION` AS PRINTER_DESCRIPTION,
        `3DMANAGER_PRINTER_STATE` AS PRINTER_STATE_ID,
        `3DMANAGER_C_STATE_PRINTER_NAME` AS PRINTER_STATE_NAME,
        `3DMANAGER_PRINTER_IMAGE_URL` AS FILE_URL,
        `3DMANAGER_PRINTER_IMAGE_KEY` AS FILE_KEY
    FROM `3DMANAGER_PRINTER` 
    LEFT JOIN `3DMANAGER_C_STATE_PRINTER` ON `3DMANAGER_C_STATE_PRINTER_ID` = `3DMANAGER_PRINTER_STATE`
<<<<<<< HEAD
    WHERE `3DMANAGER_PRINTER_GROUP_ID` = P_CD_GROUP  ;
=======
    WHERE `3DMANAGER_PRINTER_GROUP_ID` = P_CD_GROUP AND  `3DMANAGER_PRINTER_DELETED` = 0 ;
>>>>>>> release/0.2.0
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINTER_POST`(
    IN P_GROUP_ID INT,
    IN P_PRINTER_NAME VARCHAR(100),
    IN P_PRINTER_MODEL VARCHAR(100),
    IN P_PRINTER_DESCRIPTION VARCHAR(500),
    OUT CodigoError INT
)
BEGIN
	DECLARE NEW_ID INT;
    
<<<<<<< HEAD
    -- If an the proc have an error SQL while running, goes to handler, do a rollback and set "CodigoError" -1
=======
>>>>>>> release/0.2.0
    DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

<<<<<<< HEAD
		-- Independant commit
=======
		-- Forzar un commit independiente
>>>>>>> release/0.2.0
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_PRINTER_POST', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;
    
    SET CodigoError = 0;
    IF EXISTS(SELECT 1 FROM `3DMANAGER_PRINTER` WHERE `3DMANAGER_PRINTER_NAME` = P_PRINTER_NAME AND `3DMANAGER_PRINTER_GROUP_ID` = P_GROUP_ID )
    THEN
		SET CodigoError = 1;
	ELSE
		START TRANSACTION;
		INSERT INTO `3DMANAGER_PRINTER` (
			`3DMANAGER_PRINTER_NAME`,
			`3DMANAGER_PRINTER_DESCRIPTION`,
			`3DMANAGER_PRINTER_STATE`,
			`3DMANAGER_PRINTER_MODEL`,
			`3DMANAGER_PRINTER_GROUP_ID`
		) VALUES (
			P_PRINTER_NAME,
			P_PRINTER_DESCRIPTION,
			1,
			P_PRINTER_MODEL,
			P_GROUP_ID
		);
    
		SET NEW_ID = LAST_INSERT_ID();
		COMMIT;    
<<<<<<< HEAD
		SELECT `3DMANAGER_PRINTER_ID` FROM `3DMANAGER_PRINTER` WHERE NEW_ID = `3DMANAGER_PRINTER_ID`;
=======
        SELECT NEW_ID AS `3DMANAGER_PRINTER_ID`;
>>>>>>> release/0.2.0
	END IF;
END$$

CREATE PROCEDURE `3DMANAGER_pr_PRINTER_POST_IMAGE`(
    IN P_PRINTER_ID INT,
    IN P_KEY VARCHAR(255),
    IN P_URL VARCHAR(255),
    OUT CodigoError INT
)
BEGIN
<<<<<<< HEAD
    -- If an the proc have an error SQL while running, goes to handler, do a rollback and set "CodigoError" -1
=======
     -- Si hay un error SQL, se entra al handler, se hace rollback y se asigna el código -1
>>>>>>> release/0.2.0
    DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

<<<<<<< HEAD
		-- Independant commit
=======
		-- Forzar un commit independiente
>>>>>>> release/0.2.0
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_PRINTER_POST_IMAGE', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;
    
    SET CodigoError = 0;
    
	START TRANSACTION;
	UPDATE `3DMANAGER_PRINTER` 
    SET `3DMANAGER_PRINTER_IMAGE_URL` = P_URL,
		`3DMANAGER_PRINTER_IMAGE_KEY` = P_KEY
        WHERE `3DMANAGER_PRINTER_ID` = P_PRINTER_ID;	
	COMMIT;    
		SELECT `3DMANAGER_PRINTER_ID` FROM `3DMANAGER_PRINTER` WHERE P_PRINTER_ID = `3DMANAGER_PRINTER_ID`;
END$$

<<<<<<< HEAD
CREATE PROCEDURE `3DMANAGER_pr_USER_INVITATION`(
=======
CREATE PROCEDURE `3DMANAGER_pr_PRINTER_UPDATE`(
    IN P_CD_GROUP INT,
    IN P_CD_PRINTER INT,
    IN P_CD_STATE INT,
    IN P_DS_NAME VARCHAR(100),
    IN P_DS_MODEL VARCHAR(100),
    IN P_DS_DESCRIPTION VARCHAR(100),
    OUT CodigoError INT
)
BEGIN

	DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_PRINTER_UPDATE', v_err_msg);
		COMMIT;
		
		SET CodigoError = -1;
		ROLLBACK;
	END;
    SET CodigoError = 0;
	START TRANSACTION;
		UPDATE `3DMANAGER_PRINTER` 
        SET `3DMANAGER_PRINTER_STATE` = P_CD_STATE ,
         `3DMANAGER_PRINTER_NAME` = P_DS_NAME ,
         `3DMANAGER_PRINTER_MODEL` = P_DS_MODEL ,
         `3DMANAGER_PRINTER_DESCRIPTION` = P_DS_DESCRIPTION 
        WHERE `3DMANAGER_PRINTER_ID` = P_CD_PRINTER AND `3DMANAGER_PRINTER_GROUP_ID` = P_CD_GROUP;
        
        SELECT ROW_COUNT() AS Total;
    COMMIT;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_DELETE_IMAGE`(
>>>>>>> release/0.2.0
    IN P_CD_GROUP INT,
    IN P_CD_USER INT
)
BEGIN
<<<<<<< HEAD
=======
    DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_USER_DELETE_IMAGE', v_err_msg);
		COMMIT;

		ROLLBACK;
	END;
    
	START TRANSACTION;
	UPDATE `3DMANAGER_USER` SET
        `USER_IMAGE_URL` = NULL,
        `USER_IMAGE_KEY` = NULL
    WHERE `USER_GROUP_ID` = P_CD_GROUP and  `USER_ID` = P_CD_USER ;
	COMMIT;    
		SELECT `USER_ID` FROM `3DMANAGER_USER` WHERE P_CD_USER = `USER_ID`;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_DETAIL_GET`(
    IN P_CD_GROUP INT,
    IN P_CD_USER INT
)
BEGIN
	SELECT 
		U.`USER_ID`,
        U.`USER_NAME`,
        R.`3DMANAGER_C_ROLES_NAME` AS USER_ROLE,
        U.`USER_EMAIL`,
        U.`USER_REGISTER_DATE` AS USER_CREATE_DATE,
        (SELECT COUNT(*) 
			FROM `3DMANAGER_3DPRINT`
            WHERE `3DMANAGER_3DPRINT_USER_ID` = P_CD_USER 
				AND `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP ) AS USER_TOTAL_PRINTS,
         (SELECT SUM(`3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME`)/3600 
			FROM `3DMANAGER_3DPRINT`
			WHERE  `3DMANAGER_3DPRINT_USER_ID` = P_CD_USER 
				AND `3DMANAGER_3DPRINT_GROUP_ID`= P_CD_GROUP  
                AND `3DMANAGER_3DPRINT_REGISTER_DATE` > DATE_SUB(CURDATE(), INTERVAL 1 MONTH)) AS USER_PRINT_HOURS,
        (SELECT COUNT(*) 
			FROM `3DMANAGER_3DPRINT` 
			WHERE `3DMANAGER_3DPRINT_USER_ID` = P_CD_USER 
            AND `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP
			AND `3DMANAGER_3DPRINT_REGISTER_DATE` > DATE_SUB(CURDATE(), INTERVAL 1 MONTH)) AS USER_PRINTED_PRINTS,
        (SELECT SUM(`3DMANAGER_3DPRINT_REAL_IMPRESSION_TIME`)/3600 
			FROM `3DMANAGER_3DPRINT`
			WHERE  `3DMANAGER_3DPRINT_USER_ID` = P_CD_USER 
				AND `3DMANAGER_3DPRINT_GROUP_ID`= P_CD_GROUP ) AS USER_TOTAL_HOURS,
        `USER_IMAGE_URL` AS FILE_URL,
        `USER_IMAGE_KEY` AS FILE_KEY
        FROM `3DMANAGER_USER` U LEFT JOIN `3DMANAGER_C_ROLES` R ON  U.`USER_ROLE` = R.`3DMANAGER_C_ROLES_ID`
        WHERE `USER_ID` = P_CD_USER AND `USER_GROUP_ID` = P_CD_GROUP;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_GET_BY_ID`(
    IN P_CD_USER INT
)
BEGIN
    SELECT 
		u.USER_ID,
        u.USER_NAME,
        u.USER_PASSWORD,
        u.USER_EMAIL,
        u.USER_GROUP_ID,
        r.`3DMANAGER_C_ROLES_NAME` AS USER_ROLE,
        g.`3DMANAGER_GROUP_NAME` AS GROUP_NAME
        
    FROM `3DMANAGER_USER` AS u
    LEFT JOIN `3DMANAGER_C_ROLES` AS r 
        ON u.USER_ROLE = r.`3DMANAGER_C_ROLES_ID`
	LEFT JOIN `3DMANAGER_GROUP` AS g
		ON G.`3DMANAGER_GROUP_ID` = u.USER_GROUP_ID 
    WHERE u.USER_ID= P_CD_USER;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_GET_IMAGE`(
    IN P_CD_GROUP INT,
    IN P_CD_USER INT
)
BEGIN

	SELECT 
        `USER_IMAGE_URL` AS FILE_URL,
        `USER_IMAGE_KEY` AS FILE_KEY
    FROM `3DMANAGER_USER` 
    WHERE `USER_GROUP_ID` = P_CD_GROUP and  `USER_ID` = P_CD_USER ;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_GROUP_GET_BY_ID`(
    IN P_CD_USER INT
)
BEGIN
    SELECT 
        u.USER_GROUP_ID
    FROM `3DMANAGER_USER` AS u
    WHERE u.USER_ID= P_CD_USER;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_INVITATION`(
    IN P_CD_GROUP INT,
    IN P_CD_USER INT,
    OUT CodigoError INT
)
BEGIN
	SET CodigoError = 0; 
>>>>>>> release/0.2.0
    IF NOT EXISTS (
        SELECT 1 
        FROM `3DMANAGER_INVITATIONS` 
        WHERE `3DMANAGER_INVITATIONS_USER_ID` = P_CD_USER 
          AND `3DMANAGER_INVITATIONS_GROUP_ID` = P_CD_GROUP
    ) THEN
        INSERT INTO `3DMANAGER_INVITATIONS` (
            `3DMANAGER_INVITATIONS_USER_ID`,
            `3DMANAGER_INVITATIONS_GROUP_ID`
        )
        VALUES (P_CD_USER, P_CD_GROUP);
<<<<<<< HEAD
=======
        
        SELECT LAST_INSERT_ID();
	ELSE 
		SET CodigoError = 409; 
>>>>>>> release/0.2.0
    END IF;
	
END$$

<<<<<<< HEAD
CREATE PROCEDURE `3DMANAGER_pr_USER_INVITATION_LIST`()
BEGIN
	SELECT
=======
CREATE PROCEDURE `3DMANAGER_pr_USER_INVITATION_LIST`(
	IN P_FILTER VARCHAR(100)
)
BEGIN
	SELECT 
>>>>>>> release/0.2.0
		USER_ID,
        USER_NAME
    FROM `3DMANAGER_USER` 
    WHERE USER_GROUP_ID IS NULL
<<<<<<< HEAD
    ;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_LIST`(
    IN P_CD_GROUP INT,
    OUT CodigoError INT
=======
    AND (P_FILTER IS NULL OR USER_NAME LIKE CONCAT('%', P_FILTER, '%'))
    ORDER BY USER_NAME
    LIMIT 50;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_LIST`(
    IN P_CD_GROUP INT
>>>>>>> release/0.2.0
)
BEGIN
	SELECT 
		USER_ID,
        USER_NAME,
        IFNULL((SELECT SUM(`3DMANAGER_3DPRINT_IMPRESSION_TIME`) FROM `3DMANAGER_3DPRINT` WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP AND `3DMANAGER_3DPRINT_USER_ID` = USER_ID ),0) AS USER_HOURS,
        (SELECT COUNT(*) FROM `3DMANAGER_3DPRINT` WHERE `3DMANAGER_3DPRINT_GROUP_ID` = P_CD_GROUP AND `3DMANAGER_3DPRINT_USER_ID` = USER_ID ) AS NUMBER_PRINTS
    FROM `3DMANAGER_USER`
    WHERE USER_GROUP_ID = P_CD_GROUP ;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_LOGIN`(
    IN P_DS_USER_NAME VARCHAR(100)
)
BEGIN
    SELECT 
		u.USER_ID,
        u.USER_NAME,
        u.USER_PASSWORD,
        u.USER_EMAIL,
        u.USER_GROUP_ID,
        r.`3DMANAGER_C_ROLES_NAME` AS USER_ROLE,
        g.`3DMANAGER_GROUP_NAME` AS GROUP_NAME
        
    FROM `3DMANAGER_USER` AS u
    LEFT JOIN `3DMANAGER_C_ROLES` AS r 
        ON u.USER_ROLE = r.`3DMANAGER_C_ROLES_ID`
	LEFT JOIN `3DMANAGER_GROUP` AS g
<<<<<<< HEAD
		ON g.`3DMANAGER_GROUP_ID` = u.USER_GROUP_ID 
=======
		ON G.`3DMANAGER_GROUP_ID` = u.USER_GROUP_ID 
>>>>>>> release/0.2.0
    WHERE u.USER_NAME = P_DS_USER_NAME;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_POST`(
    IN P_DS_USER_NAME VARCHAR(100),
    IN P_DS_USER_PASSWORD VARCHAR(255),
    IN P_DS_USER_EMAIL VARCHAR(100),
    OUT CodigoError INT
)
BEGIN

<<<<<<< HEAD
	-- If an the proc have an error SQL while running, goes to handler, do a rollback and set "CodigoError" -1
    DECLARE v_err_msg TEXT;
=======
	DECLARE v_err_msg TEXT;
>>>>>>> release/0.2.0
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

<<<<<<< HEAD
		-- Independant commit
=======
		-- Forzar un commit independiente
>>>>>>> release/0.2.0
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_USER_POST', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;
    
    SET CodigoError = 0;
	START TRANSACTION;
		IF EXISTS (
			SELECT 1 FROM `3DMANAGER_USER` WHERE USER_NAME = P_DS_USER_NAME
		) THEN
			SET CodigoError = 4091;
		ELSEIF EXISTS (
			SELECT 1 FROM `3DMANAGER_USER` WHERE USER_EMAIL = P_DS_USER_EMAIL
		) THEN
			SET CodigoError = 4092;
		ELSE
			INSERT INTO `3DMANAGER_USER` (USER_NAME,USER_PASSWORD, USER_EMAIL)
			VALUES (P_DS_USER_NAME, P_DS_USER_PASSWORD, P_DS_USER_EMAIL);
			
<<<<<<< HEAD
			SELECT USER_NAME FROM `3DMANAGER_USER` WHERE P_DS_USER_NAME = USER_NAME;
=======
			SELECT USER_ID FROM `3DMANAGER_USER` WHERE P_DS_USER_NAME = USER_NAME;
>>>>>>> release/0.2.0
		END IF;
	COMMIT;
END$$

<<<<<<< HEAD
=======
CREATE PROCEDURE `3DMANAGER_pr_USER_POST_IMAGE`(
    IN P_USER_ID INT,
    IN P_KEY VARCHAR(255),
    IN P_URL VARCHAR(255),
    OUT CodigoError INT
)
BEGIN
     -- Si hay un error SQL, se entra al handler, se hace rollback y se asigna el código -1
    DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_USER_POST_IMAGE', v_err_msg);
		COMMIT;

		SET CodigoError = -1;
		ROLLBACK;
	END;
    
    SET CodigoError = 0;
    
	START TRANSACTION;
	UPDATE `3DMANAGER_USER` 
    SET `USER_IMAGE_URL` = P_URL,
		`USER_IMAGE_KEY` = P_KEY
        WHERE `USER_ID` = P_USER_ID;	
	COMMIT;    
		SELECT USER_ID FROM `3DMANAGER_USER` WHERE P_USER_ID = USER_ID;
END$$

CREATE PROCEDURE `3DMANAGER_pr_USER_UPDATE`(
    IN P_CD_GROUP INT,
    IN P_CD_USER INT,
    IN P_DS_NAME VARCHAR(100),
    IN P_DS_EMAIL VARCHAR(100),
    OUT CodigoError INT
)
BEGIN

	DECLARE v_err_msg TEXT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 v_err_msg = MESSAGE_TEXT;

		-- Forzar un commit independiente
		START TRANSACTION;
		INSERT INTO `3DMANAGER_SYSTEM_LOGS`(PROCEDURE_NAME, ERROR_MESSAGE)
		VALUES('3DMANAGER_pr_USER_UPDATE', v_err_msg);
		COMMIT;
		
		SET CodigoError = -1;
		ROLLBACK;
	END;
    SET CodigoError = 0;
	START TRANSACTION;
		UPDATE `3DMANAGER_USER` 
        SET `USER_NAME` = P_DS_NAME ,
         `USER_EMAIL` = P_DS_EMAIL 
        WHERE `USER_ID` = P_CD_USER AND `USER_GROUP_ID` = P_CD_GROUP;
        
        SELECT ROW_COUNT() AS Total;
    COMMIT;
END$$
>>>>>>> release/0.2.0
DELIMITER ;

